// Code generated by tools/property-attributes/generate.mjs from catalog.json. DO NOT EDIT.
//
// zz_catalog.gen.go — сгенерировано из tools/property-attributes/catalog.json.
// НЕ редактировать вручную. Чтобы регенерировать:
//
//	cd tools/property-attributes && node generate.mjs
//
// (или из корня монорепо: npm --prefix tools/property-attributes run generate)
//
// Самодостаточный модуль: объявляет fieldDef/attrKind, карты полей, функции
// валидации и функции русских подписей (PropertyTypeLabel, AttributeFieldLabel,
// AttributeEnumLabel) для экспорта (XLSX и т.п.).
//
// РАЗМЕЩЕНИЕ: артефакт эмитится как zz_catalog.gen.go.txt (а не .go), потому что
// он повторно объявляет символы, которые сейчас ещё есть в hand-written
// attributes.go. Если положить .go-файл прямо в пакет domain, возникнет коллизия
// каждого символа и сборка бэкенда сломается. Суффикс .go.txt держит артефакт в
// репо (ревьюимый, сравнимый), но вне поля зрения компилятора Go. Шаг миграции
// 1.4b удаляет дубликаты из attributes.go и переименовывает этот файл обратно в
// zz_catalog.gen.go, после чего он становится единственной реализацией.

package domain

import (
	"fmt"
	"slices"
	"sort"
	"time"
	"unicode/utf8"
)

// attrKind classifies a catalog field's value type.
type attrKind int

const (
	kindNumber attrKind = iota
	kindInteger
	kindString
	kindEnum
)

// fieldDef internally describes each catalog field.
type fieldDef struct {
	kind       attrKind
	minFloat   float64           // for kindNumber
	maxFloat   float64           // for kindNumber
	minInt     int               // for kindInteger
	maxInt     int               // for kindInteger
	maxLen     int               // for kindString
	enumVals   []string          // for kindEnum (stored values, e.g. "studio")
	label      string            // Russian display label for the field (from catalog.json)
	enumLabels map[string]string // for kindEnum: stored value -> Russian label (from catalog.json)
}

// maxYearBuilt returns the upper bound (inclusive) for the year_built field:
// the current year + 5.
func maxYearBuilt() int {
	return time.Now().UTC().Year() + 5
}

var (
	apartmentFields = map[string]fieldDef{
		"area_total":     {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Общая площадь"},
		"area_living":    {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Жилая площадь"},
		"area_kitchen":   {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Площадь кухни"},
		"floor":          {kind: kindInteger, minInt: -3, maxInt: 200, label: "Этаж"},
		"floors_total":   {kind: kindInteger, minInt: 1, maxInt: 200, label: "Этажность дома"},
		"bathroom":       {kind: kindEnum, enumVals: []string{"combined", "separate", "multiple"}, enumLabels: map[string]string{"combined": "Совмещенный", "separate": "Раздельный", "multiple": "Несколько"}, label: "Санузел"},
		"balcony":        {kind: kindEnum, enumVals: []string{"none", "balcony", "loggia", "balcony_and_loggia"}, enumLabels: map[string]string{"none": "Нет", "balcony": "Балкон", "loggia": "Лоджия", "balcony_and_loggia": "Балкон и лоджия"}, label: "Балкон"},
		"renovation":     {kind: kindEnum, enumVals: []string{"cosmetic", "euro", "design", "required"}, enumLabels: map[string]string{"cosmetic": "Косметический", "euro": "Евро", "design": "Дизайнерский", "required": "Требуется"}, label: "Ремонт"},
		"year_built":     {kind: kindInteger, minInt: 1800, maxInt: maxYearBuilt(), label: "Год постройки"},
		"ceiling_height": {kind: kindNumber, minFloat: 2, maxFloat: 10, label: "Высота потолков"},
		"parking_type":   {kind: kindEnum, enumVals: []string{"closed", "underground", "open"}, enumLabels: map[string]string{"closed": "Закрытая", "underground": "Подземная", "open": "Открытая"}, label: "Парковка"},
	}

	roomFields = map[string]fieldDef{
		"area_total":   {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Общая площадь"},
		"area_kitchen": {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Площадь кухни"},
		"floor":        {kind: kindInteger, minInt: -3, maxInt: 200, label: "Этаж"},
		"floors_total": {kind: kindInteger, minInt: 1, maxInt: 200, label: "Этажность дома"},
		"bathroom":     {kind: kindEnum, enumVals: []string{"combined", "separate", "multiple"}, enumLabels: map[string]string{"combined": "Совмещенный", "separate": "Раздельный", "multiple": "Несколько"}, label: "Санузел"},
		"balcony":      {kind: kindEnum, enumVals: []string{"none", "balcony", "loggia", "balcony_and_loggia"}, enumLabels: map[string]string{"none": "Нет", "balcony": "Балкон", "loggia": "Лоджия", "balcony_and_loggia": "Балкон и лоджия"}, label: "Балкон"},
		"renovation":   {kind: kindEnum, enumVals: []string{"cosmetic", "euro", "design", "required"}, enumLabels: map[string]string{"cosmetic": "Косметический", "euro": "Евро", "design": "Дизайнерский", "required": "Требуется"}, label: "Ремонт"},
		"year_built":   {kind: kindInteger, minInt: 1800, maxInt: maxYearBuilt(), label: "Год постройки"},
	}

	studioFields = map[string]fieldDef{
		"area_total":     {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Общая площадь"},
		"area_living":    {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Жилая площадь"},
		"area_kitchen":   {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Площадь кухни"},
		"floor":          {kind: kindInteger, minInt: -3, maxInt: 200, label: "Этаж"},
		"floors_total":   {kind: kindInteger, minInt: 1, maxInt: 200, label: "Этажность дома"},
		"bathroom":       {kind: kindEnum, enumVals: []string{"combined", "separate", "multiple"}, enumLabels: map[string]string{"combined": "Совмещенный", "separate": "Раздельный", "multiple": "Несколько"}, label: "Санузел"},
		"balcony":        {kind: kindEnum, enumVals: []string{"none", "balcony", "loggia", "balcony_and_loggia"}, enumLabels: map[string]string{"none": "Нет", "balcony": "Балкон", "loggia": "Лоджия", "balcony_and_loggia": "Балкон и лоджия"}, label: "Балкон"},
		"renovation":     {kind: kindEnum, enumVals: []string{"cosmetic", "euro", "design", "required"}, enumLabels: map[string]string{"cosmetic": "Косметический", "euro": "Евро", "design": "Дизайнерский", "required": "Требуется"}, label: "Ремонт"},
		"year_built":     {kind: kindInteger, minInt: 1800, maxInt: maxYearBuilt(), label: "Год постройки"},
		"ceiling_height": {kind: kindNumber, minFloat: 2, maxFloat: 10, label: "Высота потолков"},
		"parking_type":   {kind: kindEnum, enumVals: []string{"closed", "underground", "open"}, enumLabels: map[string]string{"closed": "Закрытая", "underground": "Подземная", "open": "Открытая"}, label: "Парковка"},
	}

	houseFields = map[string]fieldDef{
		"land_area":    {kind: kindNumber, minFloat: 0.01, maxFloat: 1000000, label: "Площадь участка"},
		"land_type":    {kind: kindEnum, enumVals: []string{"izhs", "garden", "farm"}, enumLabels: map[string]string{"izhs": "ИЖС", "garden": "Садовый", "farm": "Фермерский"}, label: "Тип участка"},
		"area_total":   {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Общая площадь"},
		"floors_total": {kind: kindInteger, minInt: 1, maxInt: 200, label: "Этажность дома"},
		"rooms":        {kind: kindEnum, enumVals: []string{"1", "2", "3", "4", "5", "6", "7_plus"}, enumLabels: map[string]string{"1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7_plus": "7+"}, label: "Комнаты"},
		"house_type":   {kind: kindEnum, enumVals: []string{"detached", "part", "townhouse", "duplex"}, enumLabels: map[string]string{"detached": "Отдельный", "part": "Часть дома", "townhouse": "Таунхаус", "duplex": "Дуплекс"}, label: "Тип дома"},
		"material":     {kind: kindEnum, enumVals: []string{"brick", "monolithic", "panel", "brick_monolithic", "block", "wooden", "reinforced_concrete"}, enumLabels: map[string]string{"brick": "Кирпичный", "monolithic": "Монолитный", "panel": "Панельный", "brick_monolithic": "Кирпично-монолитный", "block": "Блочный", "wooden": "Деревянный", "reinforced_concrete": "Железобетонный"}, label: "Материал"},
		"bathroom":     {kind: kindEnum, enumVals: []string{"indoor", "outdoor", "none"}, enumLabels: map[string]string{"indoor": "В доме", "outdoor": "На улице", "none": "Нет"}, label: "Санузел"},
		"shower":       {kind: kindEnum, enumVals: []string{"indoor", "outdoor", "none"}, enumLabels: map[string]string{"indoor": "В доме", "outdoor": "На улице", "none": "Нет"}, label: "Душ"},
		"year_built":   {kind: kindInteger, minInt: 1800, maxInt: maxYearBuilt(), label: "Год постройки"},
	}

	officeFields = map[string]fieldDef{
		"building_type": {kind: kindEnum, enumVals: []string{"business_center", "warehouse_building", "shopping_center", "detached", "residential"}, enumLabels: map[string]string{"business_center": "Бизнес-центр", "warehouse_building": "Складское здание", "shopping_center": "Торговый центр", "detached": "Отдельное здание", "residential": "Жилой дом"}, label: "Тип здания"},
		"floor":         {kind: kindInteger, minInt: -3, maxInt: 200, label: "Этаж"},
		"floors_total":  {kind: kindInteger, minInt: 1, maxInt: 200, label: "Этажность дома"},
		"area_total":    {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Общая площадь"},
		"rooms":         {kind: kindEnum, enumVals: []string{"1", "2", "3", "4", "5", "6", "7_plus"}, enumLabels: map[string]string{"1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7_plus": "7+"}, label: "Комнаты"},
		"entrance":      {kind: kindEnum, enumVals: []string{"separate", "common"}, enumLabels: map[string]string{"separate": "Отдельный", "common": "Общий"}, label: "Вход"},
		"renovation":    {kind: kindEnum, enumVals: []string{"cosmetic", "euro", "design", "required"}, enumLabels: map[string]string{"cosmetic": "Косметический", "euro": "Евро", "design": "Дизайнерский", "required": "Требуется"}, label: "Ремонт"},
	}

	warehouseFields = map[string]fieldDef{
		"area_total":    {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Общая площадь"},
		"entrance":      {kind: kindEnum, enumVals: []string{"separate", "common"}, enumLabels: map[string]string{"separate": "Отдельный", "common": "Общий"}, label: "Вход"},
		"building_type": {kind: kindEnum, enumVals: []string{"business_center", "warehouse_building", "shopping_center", "detached", "residential"}, enumLabels: map[string]string{"business_center": "Бизнес-центр", "warehouse_building": "Складское здание", "shopping_center": "Торговый центр", "detached": "Отдельное здание", "residential": "Жилой дом"}, label: "Тип здания"},
	}

	garageFields = map[string]fieldDef{
		"area_total": {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Общая площадь"},
		"material":   {kind: kindEnum, enumVals: []string{"brick", "metal", "reinforced_concrete"}, enumLabels: map[string]string{"brick": "Кирпичный", "metal": "Металлический", "reinforced_concrete": "Железобетонный"}, label: "Материал"},
	}

	parkingFields = map[string]fieldDef{
		"area_total":       {kind: kindNumber, minFloat: 1, maxFloat: 100000, label: "Общая площадь"},
		"parking_location": {kind: kindEnum, enumVals: []string{"underground", "indoor", "outdoor"}, enumLabels: map[string]string{"underground": "Подземная", "indoor": "Крытая", "outdoor": "Открытая"}, label: "Расположение"},
		"parking_level":    {kind: kindInteger, minInt: -5, maxInt: 100, label: "Уровень"},
		"spot_number":      {kind: kindString, maxLen: 50, label: "Номер места"},
	}

	landFields = map[string]fieldDef{
		"land_area": {kind: kindNumber, minFloat: 0.01, maxFloat: 1000000, label: "Площадь участка"},
		"land_type": {kind: kindEnum, enumVals: []string{"izhs", "garden", "farm"}, enumLabels: map[string]string{"izhs": "ИЖС", "garden": "Садовый", "farm": "Фермерский"}, label: "Тип участка"},
	}
	// apartmentsFields mirrors apartmentFields (the "apartments" type shares the apartment field set).
	apartmentsFields = apartmentFields
	// commercialFields mirrors officeFields (the "commercial" type shares the office field set).
	commercialFields = officeFields
)

// fieldsForType returns the catalog field map for the given property type.
// All eleven property types are covered. Returns nil only for an unknown type.
func fieldsForType(t PropertyType) map[string]fieldDef {
	switch t {
	case PropertyTypeApartment, PropertyTypeApartments:
		return apartmentFields
	case PropertyTypeStudio:
		return studioFields
	case PropertyTypeRoom:
		return roomFields
	case PropertyTypeHouse:
		return houseFields
	case PropertyTypeOffice:
		return officeFields
	case PropertyTypeCommercial:
		return commercialFields
	case PropertyTypeWarehouse:
		return warehouseFields
	case PropertyTypeGarage:
		return garageFields
	case PropertyTypeParking:
		return parkingFields
	case PropertyTypeLand:
		return landFields
	default:
		return nil
	}
}

// CatalogKeys returns the set of catalog attribute keys for the given property
// type. Returns nil for an unknown type.
func CatalogKeys(propType PropertyType) []string {
	fields := fieldsForType(propType)
	if fields == nil {
		return nil
	}
	keys := make([]string, 0, len(fields))
	for k := range fields {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// FilterByType returns a copy of attrs containing only keys that belong to the
// catalog of the given property type. Unknown keys are silently dropped. This
// implements the "current type determines the meaning of stored keys" read
// semantics: when the type changes, keys of the old type become inert.
func (a Attributes) FilterByType(propType PropertyType) Attributes {
	fields := fieldsForType(propType)
	out := make(Attributes, len(a))
	for k, v := range a {
		if _, ok := fields[k]; ok {
			out[k] = v
		}
	}
	return out
}

// ValidateAttributes validates the given attributes against the catalog for the
// given property type. Only keys belonging to the catalog of the current type
// are accepted; unknown keys and null values are rejected. Numeric ranges,
// enum membership, and cross-field rules are checked. All eleven property types
// are supported.
func ValidateAttributes(propType PropertyType, attrs Attributes) ValidationResult {
	var res ValidationResult
	fields := fieldsForType(propType)

	// Unsupported type: every key is unknown. Empty attrs => valid (vacuous).
	if fields == nil {
		if len(attrs) == 0 {
			return res
		}
		keys := make([]string, 0, len(attrs))
		for k := range attrs {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			res.Errors = append(res.Errors, AttributeValidationError{
				Field:  k,
				Reason: fmt.Sprintf("unknown attribute for property type %s", propType),
			})
		}
		return res
	}

	// Deterministic ordering: sorted slice of catalog keys, then unknown keys.
	catKeys := make([]string, 0, len(fields))
	for k := range fields {
		catKeys = append(catKeys, k)
	}
	sort.Strings(catKeys)

	// Validate present catalog fields first.
	for _, k := range catKeys {
		v, present := attrs[k]
		if !present {
			continue
		}
		if v == nil {
			res.Errors = append(res.Errors, AttributeValidationError{
				Field:  k,
				Reason: "attribute value must not be null",
			})
			continue
		}
		def := fields[k]
		if reason := validateField(def, v); reason != "" {
			res.Errors = append(res.Errors, AttributeValidationError{
				Field:  k,
				Reason: reason,
			})
		}
	}

	// Report unknown keys (present in attrs but not in the catalog) in sorted order.
	unknownKeys := make([]string, 0)
	for k := range attrs {
		if _, ok := fields[k]; !ok {
			unknownKeys = append(unknownKeys, k)
		}
	}
	sort.Strings(unknownKeys)
	for _, k := range unknownKeys {
		res.Errors = append(res.Errors, AttributeValidationError{
			Field:  k,
			Reason: fmt.Sprintf("unknown attribute for property type %s", propType),
		})
	}

	// Cross-field validations (only when BOTH sides are present).
	res.Errors = append(res.Errors, crossFieldErrors(propType, fields, attrs)...)

	return res
}

// validateField checks a single present field against its definition and returns
// a non-empty reason string on failure, or "" when valid.
func validateField(def fieldDef, v any) string {
	switch def.kind {
	case kindNumber:
		f, ok := v.(float64)
		if !ok {
			return "expected a number"
		}
		if f < def.minFloat || f > def.maxFloat {
			return fmt.Sprintf("must be between %g and %g", def.minFloat, def.maxFloat)
		}
	case kindInteger:
		f, ok := v.(float64)
		if !ok {
			return "expected an integer"
		}
		if f != float64(int64(f)) {
			return "expected an integer"
		}
		i := int(f)
		if i < def.minInt || i > def.maxInt {
			return fmt.Sprintf("must be between %d and %d", def.minInt, def.maxInt)
		}
	case kindString:
		s, ok := v.(string)
		if !ok {
			return "expected a string"
		}
		if utf8.RuneCountInString(s) > def.maxLen {
			return fmt.Sprintf("must be at most %d characters", def.maxLen)
		}
	case kindEnum:
		s, ok := v.(string)
		if !ok {
			return "expected a string"
		}
		if !slices.Contains(def.enumVals, s) {
			return fmt.Sprintf("must be one of %v", def.enumVals)
		}
	}
	return ""
}

// crossFieldErrors returns errors for cross-field rules, evaluated only when
// BOTH sides of a comparison are present and individually valid.
func crossFieldErrors(propType PropertyType, fields map[string]fieldDef, attrs Attributes) []AttributeValidationError {
	var errs []AttributeValidationError

	numVal := func(key string) (float64, bool) {
		def, inCatalog := fields[key]
		if !inCatalog {
			return 0, false
		}
		v, present := attrs[key]
		if !present || v == nil {
			return 0, false
		}
		if def.kind != kindNumber && def.kind != kindInteger {
			return 0, false
		}
		f, ok := v.(float64)
		if !ok {
			return 0, false
		}
		// Only consider the value valid if it passes its own range/type check,
		// so a cross-field error isn't produced on top of a field-level error.
		if reason := validateField(def, v); reason != "" {
			return 0, false
		}
		return f, true
	}

	switch propType {
	case PropertyTypeApartment, PropertyTypeApartments, PropertyTypeStudio:
		if f, ok := numVal("floor"); ok {
			if ft, ok2 := numVal("floors_total"); ok2 && f > ft {
				errs = append(errs, AttributeValidationError{
					Field:  "floor",
					Reason: "floor must not exceed floors_total",
				})
			}
		}

		if al, ok := numVal("area_living"); ok {
			if at, ok2 := numVal("area_total"); ok2 && al > at {
				errs = append(errs, AttributeValidationError{
					Field:  "area_living",
					Reason: "area_living must not exceed area_total",
				})
			}
		}

		if ak, ok := numVal("area_kitchen"); ok {
			if at, ok2 := numVal("area_total"); ok2 && ak > at {
				errs = append(errs, AttributeValidationError{
					Field:  "area_kitchen",
					Reason: "area_kitchen must not exceed area_total",
				})
			}
		}

	case PropertyTypeRoom:
		if f, ok := numVal("floor"); ok {
			if ft, ok2 := numVal("floors_total"); ok2 && f > ft {
				errs = append(errs, AttributeValidationError{
					Field:  "floor",
					Reason: "floor must not exceed floors_total",
				})
			}
		}

		if ak, ok := numVal("area_kitchen"); ok {
			if at, ok2 := numVal("area_total"); ok2 && ak > at {
				errs = append(errs, AttributeValidationError{
					Field:  "area_kitchen",
					Reason: "area_kitchen must not exceed area_total",
				})
			}
		}

	case PropertyTypeOffice, PropertyTypeCommercial:
		if f, ok := numVal("floor"); ok {
			if ft, ok2 := numVal("floors_total"); ok2 && f > ft {
				errs = append(errs, AttributeValidationError{
					Field:  "floor",
					Reason: "floor must not exceed floors_total",
				})
			}
		}

	default:
		// Unsupported types have no cross-field rules yet.
	}

	return errs
}

// PropertyTypeLabel returns the Russian display label for a property type
// (e.g. PropertyTypeApartment -> "Квартира"), sourced from catalog.json
// types.<key>.label. Returns an empty string for an unknown type so export
// pipelines degrade gracefully instead of crashing on unexpected values.
func PropertyTypeLabel(propType PropertyType) string {
	switch propType {
	case PropertyTypeApartment:
		return "Квартира"
	case PropertyTypeRoom:
		return "Комната"
	case PropertyTypeApartments:
		return "Апартаменты"
	case PropertyTypeStudio:
		return "Студия"
	case PropertyTypeHouse:
		return "Дом"
	case PropertyTypeOffice:
		return "Офис"
	case PropertyTypeCommercial:
		return "Коммерческое помещение"
	case PropertyTypeWarehouse:
		return "Склад"
	case PropertyTypeGarage:
		return "Гараж"
	case PropertyTypeParking:
		return "Машиноместо"
	case PropertyTypeLand:
		return "Земельный участок"
	default:
		return ""
	}
}

// AttributeFieldLabel returns the Russian display label for a catalog field
// in the context of a specific property type (e.g. for PropertyTypeApartment,
// "rooms" -> "Комнаты"). The lookup is type-scoped because the same field key
// (e.g. "bathroom") can carry different option sets per type. Returns an empty
// string when the type is unknown or the field is not part of that type's
// catalog.
func AttributeFieldLabel(propType PropertyType, fieldKey string) string {
	fields := fieldsForType(propType)
	if fields == nil {
		return ""
	}
	return fields[fieldKey].label
}

// AttributeEnumLabel returns the Russian display label for an enum option
// value of a catalog field in the context of a specific property type (e.g. for
// PropertyTypeApartment, field "bathroom", option "combined" -> "Совмещенный").
// Returns an empty string when the type, field, or option is unknown, or when
// the field is not an enum.
func AttributeEnumLabel(propType PropertyType, fieldKey, optionKey string) string {
	fields := fieldsForType(propType)
	if fields == nil {
		return ""
	}
	def, ok := fields[fieldKey]
	if !ok || def.kind != kindEnum {
		return ""
	}
	return def.enumLabels[optionKey]
}
