// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for MeResponseRole.
const (
	Admin MeResponseRole = "admin"
	Owner MeResponseRole = "owner"
)

// Defines values for PropertyCreateRequestType.
const (
	PropertyCreateRequestTypeApartment  PropertyCreateRequestType = "apartment"
	PropertyCreateRequestTypeApartments PropertyCreateRequestType = "apartments"
	PropertyCreateRequestTypeCommercial PropertyCreateRequestType = "commercial"
	PropertyCreateRequestTypeGarage     PropertyCreateRequestType = "garage"
	PropertyCreateRequestTypeHouse      PropertyCreateRequestType = "house"
	PropertyCreateRequestTypeLand       PropertyCreateRequestType = "land"
	PropertyCreateRequestTypeOffice     PropertyCreateRequestType = "office"
	PropertyCreateRequestTypeParking    PropertyCreateRequestType = "parking"
	PropertyCreateRequestTypeRoom       PropertyCreateRequestType = "room"
	PropertyCreateRequestTypeWarehouse  PropertyCreateRequestType = "warehouse"
)

// Defines values for PropertyResponseStatus.
const (
	PropertyResponseStatusActive      PropertyResponseStatus = "active"
	PropertyResponseStatusArchived    PropertyResponseStatus = "archived"
	PropertyResponseStatusMaintenance PropertyResponseStatus = "maintenance"
)

// Defines values for PropertyResponseType.
const (
	PropertyResponseTypeApartment  PropertyResponseType = "apartment"
	PropertyResponseTypeApartments PropertyResponseType = "apartments"
	PropertyResponseTypeCommercial PropertyResponseType = "commercial"
	PropertyResponseTypeGarage     PropertyResponseType = "garage"
	PropertyResponseTypeHouse      PropertyResponseType = "house"
	PropertyResponseTypeLand       PropertyResponseType = "land"
	PropertyResponseTypeOffice     PropertyResponseType = "office"
	PropertyResponseTypeParking    PropertyResponseType = "parking"
	PropertyResponseTypeRoom       PropertyResponseType = "room"
	PropertyResponseTypeWarehouse  PropertyResponseType = "warehouse"
)

// Defines values for PropertyUpdateRequestStatus.
const (
	PropertyUpdateRequestStatusActive      PropertyUpdateRequestStatus = "active"
	PropertyUpdateRequestStatusMaintenance PropertyUpdateRequestStatus = "maintenance"
)

// Defines values for PropertyUpdateRequestType.
const (
	Apartment  PropertyUpdateRequestType = "apartment"
	Apartments PropertyUpdateRequestType = "apartments"
	Commercial PropertyUpdateRequestType = "commercial"
	Garage     PropertyUpdateRequestType = "garage"
	House      PropertyUpdateRequestType = "house"
	Land       PropertyUpdateRequestType = "land"
	Office     PropertyUpdateRequestType = "office"
	Parking    PropertyUpdateRequestType = "parking"
	Room       PropertyUpdateRequestType = "room"
	Warehouse  PropertyUpdateRequestType = "warehouse"
)

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Email      *string            `json:"email"`
	Id         openapi_types.UUID `json:"id"`
	Name       *string            `json:"name"`
	Patronymic *string            `json:"patronymic"`
	Phone      string             `json:"phone"`
	Role       MeResponseRole     `json:"role"`
	Surname    *string            `json:"surname"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// Problem defines model for Problem.
type Problem struct {
	Detail    *string `json:"detail,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// PropertiesResponse defines model for PropertiesResponse.
type PropertiesResponse struct {
	Items []PropertyResponse `json:"items"`
}

// PropertyCreateRequest defines model for PropertyCreateRequest.
type PropertyCreateRequest struct {
	Address     string                    `json:"address"`
	Description *string                   `json:"description,omitempty"`
	Name        string                    `json:"name"`
	Type        PropertyCreateRequestType `json:"type"`
}

// PropertyCreateRequestType defines model for PropertyCreateRequest.Type.
type PropertyCreateRequestType string

// PropertyResponse defines model for PropertyResponse.
type PropertyResponse struct {
	Address     string                 `json:"address"`
	CreatedAt   time.Time              `json:"created_at"`
	Description *string                `json:"description,omitempty"`
	Id          openapi_types.UUID     `json:"id"`
	Name        string                 `json:"name"`
	Status      PropertyResponseStatus `json:"status"`
	Type        PropertyResponseType   `json:"type"`
	UpdatedAt   time.Time              `json:"updated_at"`
}

// PropertyResponseStatus defines model for PropertyResponse.Status.
type PropertyResponseStatus string

// PropertyResponseType defines model for PropertyResponse.Type.
type PropertyResponseType string

// PropertyUpdateRequest defines model for PropertyUpdateRequest.
type PropertyUpdateRequest struct {
	Address     *string                      `json:"address,omitempty"`
	Description *string                      `json:"description,omitempty"`
	Name        *string                      `json:"name,omitempty"`
	Status      *PropertyUpdateRequestStatus `json:"status,omitempty"`
	Type        *PropertyUpdateRequestType   `json:"type,omitempty"`
}

// PropertyUpdateRequestStatus defines model for PropertyUpdateRequest.Status.
type PropertyUpdateRequestStatus string

// PropertyUpdateRequestType defines model for PropertyUpdateRequest.Type.
type PropertyUpdateRequestType string

// SendPhoneCodeRequest defines model for SendPhoneCodeRequest.
type SendPhoneCodeRequest struct {
	Phone string `json:"phone"`
}

// VerifyPhoneCodeRequest defines model for VerifyPhoneCodeRequest.
type VerifyPhoneCodeRequest struct {
	Code  string `json:"code"`
	Phone string `json:"phone"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// SendPhoneCodeJSONRequestBody defines body for SendPhoneCode for application/json ContentType.
type SendPhoneCodeJSONRequestBody = SendPhoneCodeRequest

// VerifyPhoneCodeJSONRequestBody defines body for VerifyPhoneCode for application/json ContentType.
type VerifyPhoneCodeJSONRequestBody = VerifyPhoneCodeRequest

// CreatePropertyJSONRequestBody defines body for CreateProperty for application/json ContentType.
type CreatePropertyJSONRequestBody = PropertyCreateRequest

// UpdatePropertyJSONRequestBody defines body for UpdateProperty for application/json ContentType.
type UpdatePropertyJSONRequestBody = PropertyUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (POST /auth/phone/send)
	SendPhoneCode(w http.ResponseWriter, r *http.Request)

	// (POST /auth/phone/verify)
	VerifyPhoneCode(w http.ResponseWriter, r *http.Request)

	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (GET /properties)
	ListProperties(w http.ResponseWriter, r *http.Request)

	// (POST /properties)
	CreateProperty(w http.ResponseWriter, r *http.Request)

	// (GET /properties/{id})
	GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /properties/{id})
	UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /properties/{id}/archive)
	ArchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /properties/{id}/unarchive)
	UnarchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/phone/send)
func (_ Unimplemented) SendPhoneCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/phone/verify)
func (_ Unimplemented) VerifyPhoneCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties)
func (_ Unimplemented) ListProperties(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties)
func (_ Unimplemented) CreateProperty(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties/{id})
func (_ Unimplemented) GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /properties/{id})
func (_ Unimplemented) UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{id}/archive)
func (_ Unimplemented) ArchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{id}/unarchive)
func (_ Unimplemented) UnarchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendPhoneCode operation middleware
func (siw *ServerInterfaceWrapper) SendPhoneCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendPhoneCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyPhoneCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyPhoneCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyPhoneCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProperties operation middleware
func (siw *ServerInterfaceWrapper) ListProperties(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProperties(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProperty operation middleware
func (siw *ServerInterfaceWrapper) CreateProperty(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProperty(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProperty operation middleware
func (siw *ServerInterfaceWrapper) GetProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProperty operation middleware
func (siw *ServerInterfaceWrapper) UpdateProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveProperty operation middleware
func (siw *ServerInterfaceWrapper) ArchiveProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnarchiveProperty operation middleware
func (siw *ServerInterfaceWrapper) UnarchiveProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnarchiveProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/phone/send", wrapper.SendPhoneCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/phone/verify", wrapper.VerifyPhoneCode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties", wrapper.ListProperties)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties", wrapper.CreateProperty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties/{id}", wrapper.GetProperty)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/properties/{id}", wrapper.UpdateProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{id}/archive", wrapper.ArchiveProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{id}/unarchive", wrapper.UnarchiveProperty)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYUW/bNhD+K8Ztb1Mj2U22Rm9pgA3FkiJomr0ERsGIZ4utRKoklVYL9N8HkpIsxZIt",
	"N7EXoG+SeDzefd/d8U4PEIk0Exy5VhA+gESVCa7Qvrwl9AN+zVFp8xYJrpHbR5JlCYuIZoL7n5Xg5puK",
	"YkyJefpV4gJC+MVfqfbdqvKvpLhLMIWyLD2gqCLJMqMGQnPaRFbHlR68F/pPkXN6iKPfCz1Z2MNKDz4K",
	"cUl4UXmuDnH+RyEmKeFF7b8ydtxwkutYSPYvHgSEznlmudpjVF7ihyowzFsmRYZSMxclmBKWmAeeJwm5",
	"SxBCLXP0QBcZQghKS8aXxiNm/VgImRINIeQ5o9AjxkmKo/RlREvBi5RF48Rjwa3itRUpEruAPE8hvAXx",
	"jaMEDwhNGYd5jy6Vy5FmGvX4NWfSsHgL1mVnSXXuSr24+4yRDf6apjWwKeoK7XV0udKERwMeusB6R3tX",
	"lSY6V60lxjUuUZo1zXTSr9N9eNjisF2t1TRHDThdeTocbExj2n3YEu1mb9Hoa6wGIiUp1tmxWjcYV5xL",
	"JBpbZbFrH6FUorKPKfl+gXypYwhPgqAnhjrp15GfBb0b6ohrS56ceMPM1PFMMiJ1aoqHiTmRmtCuPynw",
	"IBa5MuREIk1RRowk4IFYLFhkvn4jEmuJJZFkaR4yIr+Y0zxICKc9OfIIWWu7V0dDDdMmpIeDoAXymuuR",
	"5Yd+IrpTayjR+EqzlQ0biHhq3dqQXg0hkWb3xpaUmFTjNm89IDKK2T3S3pLzEkj1IM/ojvj2FcD+aGiQ",
	"6tDYOXNTwNxYsReemiNjYf5ys3oN/2vk9MrcaOeCDsPf3L74naSZuVLgtz9OT0+DIJhOZ7OtceP29/H/",
	"D0q2KLZbEAn6yIDp7PXxye+wQ6/Qa5TnVK/bZvjGKJdMF9fmSnJ2KFSKCX4uxBdmz2Cm/Yrcax1KtdSn",
	"dq0hGfsbC9e8Mb4Q1kB3P8OZRE7J5Coh3GTl5OzqHXhwj1K59i44mh4FxjWRIScZgxBeHwVHry3rOraW",
	"+aYD9BOxFLnDTzgcDYq22zT9A1y4da87LMyCY9egtHvKC7FcIp048RgJRWmFr1G/Wvm/al0fo20cPQ6m",
	"Q/d8Y4C/3rxWuEN4u4b47bycGxnnruXQV+hGjX6XOyEOTTv1VtDi2Vrz3jQquxFnOsxyDPBGx0QZmyyC",
	"wXYEW8Oe2TI73b7l8aTk+Gqjem9TcxjXR6m7J2QHCsQobINns6I1Q/VMX2e5jpFroxrpU5Jld6p3z6+n",
	"xYe7KZfYEw9/ob5E+N9IOM+lRK4nuXKzzx5LT/dq6gXjgim9mon2iUrP5NWDzkpqkrAfjp0xAHkD5cIN",
	"X3W/t6dq0T/pjSoW02c3YgQfxaRqluFg+b97kPsPjJab0r5FakYkSVHb6ndbdUemRVn1RrYn6pLhtYDd",
	"MqmV8/2n0jji3N8c9eNV2F39mzc1P1LHph7RUbzOkZuuDk7T/vK7Oy4euBnYKUyq+RcOeb8/f2T1FAS/",
	"+uEx3CCeOYGfsjo0f4NeOIk530rjTS3yUxLZAPSyqLRC8r4mIJcJhBBrnYW+n4iIJLFQOnwTvAmgnJf/",
	"BQAA//9VHkwlKhwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
