// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for LeaseResponseStatus.
const (
	LeaseResponseStatusActive         LeaseResponseStatus = "active"
	LeaseResponseStatusArchived       LeaseResponseStatus = "archived"
	LeaseResponseStatusAwaitingStart  LeaseResponseStatus = "awaiting_start"
	LeaseResponseStatusCompleted      LeaseResponseStatus = "completed"
	LeaseResponseStatusRequiresAction LeaseResponseStatus = "requires_action"
)

// Defines values for MeResponseRole.
const (
	Admin MeResponseRole = "admin"
	Owner MeResponseRole = "owner"
)

// Defines values for OperationCategory.
const (
	OtherExpense OperationCategory = "other_expense"
	OtherIncome  OperationCategory = "other_income"
	Rent         OperationCategory = "rent"
	Repair       OperationCategory = "repair"
	Tax          OperationCategory = "tax"
	Utilities    OperationCategory = "utilities"
)

// Defines values for OperationType.
const (
	Expense OperationType = "expense"
	Income  OperationType = "income"
)

// Defines values for PropertyCreateRequestType.
const (
	PropertyCreateRequestTypeApartment  PropertyCreateRequestType = "apartment"
	PropertyCreateRequestTypeApartments PropertyCreateRequestType = "apartments"
	PropertyCreateRequestTypeCommercial PropertyCreateRequestType = "commercial"
	PropertyCreateRequestTypeGarage     PropertyCreateRequestType = "garage"
	PropertyCreateRequestTypeHouse      PropertyCreateRequestType = "house"
	PropertyCreateRequestTypeLand       PropertyCreateRequestType = "land"
	PropertyCreateRequestTypeOffice     PropertyCreateRequestType = "office"
	PropertyCreateRequestTypeParking    PropertyCreateRequestType = "parking"
	PropertyCreateRequestTypeRoom       PropertyCreateRequestType = "room"
	PropertyCreateRequestTypeWarehouse  PropertyCreateRequestType = "warehouse"
)

// Defines values for PropertyResponseOccupancy.
const (
	Free     PropertyResponseOccupancy = "free"
	Occupied PropertyResponseOccupancy = "occupied"
)

// Defines values for PropertyResponseStatus.
const (
	PropertyResponseStatusActive      PropertyResponseStatus = "active"
	PropertyResponseStatusArchived    PropertyResponseStatus = "archived"
	PropertyResponseStatusMaintenance PropertyResponseStatus = "maintenance"
)

// Defines values for PropertyResponseType.
const (
	PropertyResponseTypeApartment  PropertyResponseType = "apartment"
	PropertyResponseTypeApartments PropertyResponseType = "apartments"
	PropertyResponseTypeCommercial PropertyResponseType = "commercial"
	PropertyResponseTypeGarage     PropertyResponseType = "garage"
	PropertyResponseTypeHouse      PropertyResponseType = "house"
	PropertyResponseTypeLand       PropertyResponseType = "land"
	PropertyResponseTypeOffice     PropertyResponseType = "office"
	PropertyResponseTypeParking    PropertyResponseType = "parking"
	PropertyResponseTypeRoom       PropertyResponseType = "room"
	PropertyResponseTypeWarehouse  PropertyResponseType = "warehouse"
)

// Defines values for PropertyUpdateRequestStatus.
const (
	PropertyUpdateRequestStatusActive      PropertyUpdateRequestStatus = "active"
	PropertyUpdateRequestStatusMaintenance PropertyUpdateRequestStatus = "maintenance"
)

// Defines values for PropertyUpdateRequestType.
const (
	Apartment  PropertyUpdateRequestType = "apartment"
	Apartments PropertyUpdateRequestType = "apartments"
	Commercial PropertyUpdateRequestType = "commercial"
	Garage     PropertyUpdateRequestType = "garage"
	House      PropertyUpdateRequestType = "house"
	Land       PropertyUpdateRequestType = "land"
	Office     PropertyUpdateRequestType = "office"
	Parking    PropertyUpdateRequestType = "parking"
	Room       PropertyUpdateRequestType = "room"
	Warehouse  PropertyUpdateRequestType = "warehouse"
)

// Defines values for RecurringOperationResponsePeriodicity.
const (
	Monthly RecurringOperationResponsePeriodicity = "monthly"
)

// Defines values for RecurringOperationResponseStatus.
const (
	RecurringOperationResponseStatusActive RecurringOperationResponseStatus = "active"
	RecurringOperationResponseStatusPaused RecurringOperationResponseStatus = "paused"
)

// Defines values for ReminderResponseEventType.
const (
	LeaseExpiring       ReminderResponseEventType = "lease_expiring"
	LeaseRequiresAction ReminderResponseEventType = "lease_requires_action"
	OperationDue        ReminderResponseEventType = "operation_due"
)

// Defines values for ReminderResponseStatus.
const (
	Cancelled ReminderResponseStatus = "cancelled"
	Failed    ReminderResponseStatus = "failed"
	Pending   ReminderResponseStatus = "pending"
	Sent      ReminderResponseStatus = "sent"
)

// Defines values for ReminderResponseTargetType.
const (
	Lease              ReminderResponseTargetType = "lease"
	Operation          ReminderResponseTargetType = "operation"
	RecurringOperation ReminderResponseTargetType = "recurring_operation"
)

// LeaseCreateRequest defines model for LeaseCreateRequest.
type LeaseCreateRequest struct {
	Comment              *string             `json:"comment,omitempty"`
	DepositAmountKopecks *int                `json:"deposit_amount_kopecks,omitempty"`
	EndDate              *openapi_types.Date `json:"end_date,omitempty"`
	PaymentDay           int                 `json:"payment_day"`
	PropertyId           openapi_types.UUID  `json:"property_id"`
	RentAmountKopecks    int                 `json:"rent_amount_kopecks"`
	StartDate            openapi_types.Date  `json:"start_date"`
	TenantContactId      *openapi_types.UUID `json:"tenant_contact_id,omitempty"`
}

// LeaseResponse defines model for LeaseResponse.
type LeaseResponse struct {
	Comment              *string                `json:"comment"`
	CreatedAt            time.Time              `json:"created_at"`
	DepositAmountKopecks int                    `json:"deposit_amount_kopecks"`
	EndDate              *openapi_types.Date    `json:"end_date"`
	Id                   openapi_types.UUID     `json:"id"`
	OwnerId              openapi_types.UUID     `json:"owner_id"`
	PaymentDay           int                    `json:"payment_day"`
	PropertyId           openapi_types.UUID     `json:"property_id"`
	RentAmountKopecks    int                    `json:"rent_amount_kopecks"`
	StartDate            openapi_types.Date     `json:"start_date"`
	Status               LeaseResponseStatus    `json:"status"`
	TenantContact        *TenantContactResponse `json:"tenant_contact"`
	UpdatedAt            time.Time              `json:"updated_at"`
}

// LeaseResponseStatus defines model for LeaseResponse.Status.
type LeaseResponseStatus string

// LeaseUpdateRequest defines model for LeaseUpdateRequest.
type LeaseUpdateRequest struct {
	Comment              *string             `json:"comment,omitempty"`
	DepositAmountKopecks *int                `json:"deposit_amount_kopecks,omitempty"`
	EndDate              *openapi_types.Date `json:"end_date,omitempty"`
	PaymentDay           *int                `json:"payment_day,omitempty"`
	RentAmountKopecks    *int                `json:"rent_amount_kopecks,omitempty"`
	StartDate            *openapi_types.Date `json:"start_date,omitempty"`
	TenantContactId      *openapi_types.UUID `json:"tenant_contact_id,omitempty"`
}

// LeasesResponse defines model for LeasesResponse.
type LeasesResponse struct {
	Items []LeaseResponse `json:"items"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Email      *string            `json:"email"`
	Id         openapi_types.UUID `json:"id"`
	Name       *string            `json:"name"`
	Patronymic *string            `json:"patronymic"`
	Phone      string             `json:"phone"`
	Role       MeResponseRole     `json:"role"`
	Surname    *string            `json:"surname"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// OperationCategory defines model for OperationCategory.
type OperationCategory string

// OperationCreateRequest defines model for OperationCreateRequest.
type OperationCreateRequest struct {
	AmountKopecks int                 `json:"amount_kopecks"`
	Category      OperationCategory   `json:"category"`
	Comment       *string             `json:"comment,omitempty"`
	LeaseId       *openapi_types.UUID `json:"lease_id,omitempty"`
	OperationDate openapi_types.Date  `json:"operation_date"`
	Type          OperationType       `json:"type"`
}

// OperationResponse defines model for OperationResponse.
type OperationResponse struct {
	AmountKopecks        int                 `json:"amount_kopecks"`
	Category             OperationCategory   `json:"category"`
	Comment              *string             `json:"comment"`
	CreatedAt            time.Time           `json:"created_at"`
	Id                   openapi_types.UUID  `json:"id"`
	IsException          bool                `json:"is_exception"`
	LeaseId              *openapi_types.UUID `json:"lease_id"`
	OperationDate        openapi_types.Date  `json:"operation_date"`
	OwnerId              openapi_types.UUID  `json:"owner_id"`
	PropertyId           openapi_types.UUID  `json:"property_id"`
	RecurringOperationId *openapi_types.UUID `json:"recurring_operation_id"`
	Type                 OperationType       `json:"type"`
	UpdatedAt            time.Time           `json:"updated_at"`
}

// OperationType defines model for OperationType.
type OperationType string

// OperationUpdateRequest defines model for OperationUpdateRequest.
type OperationUpdateRequest struct {
	AmountKopecks *int                `json:"amount_kopecks,omitempty"`
	Category      *OperationCategory  `json:"category,omitempty"`
	Comment       *string             `json:"comment,omitempty"`
	LeaseId       *openapi_types.UUID `json:"lease_id,omitempty"`
	OperationDate *openapi_types.Date `json:"operation_date,omitempty"`
	Type          *OperationType      `json:"type,omitempty"`
}

// OperationsResponse defines model for OperationsResponse.
type OperationsResponse struct {
	Items []OperationResponse `json:"items"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail    *string `json:"detail,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// PropertiesResponse defines model for PropertiesResponse.
type PropertiesResponse struct {
	Items []PropertyResponse `json:"items"`
}

// PropertyCreateRequest defines model for PropertyCreateRequest.
type PropertyCreateRequest struct {
	Address     string                    `json:"address"`
	Description *string                   `json:"description,omitempty"`
	Name        string                    `json:"name"`
	Type        PropertyCreateRequestType `json:"type"`
}

// PropertyCreateRequestType defines model for PropertyCreateRequest.Type.
type PropertyCreateRequestType string

// PropertyResponse defines model for PropertyResponse.
type PropertyResponse struct {
	Address     string                    `json:"address"`
	CreatedAt   time.Time                 `json:"created_at"`
	Description *string                   `json:"description,omitempty"`
	Id          openapi_types.UUID        `json:"id"`
	Name        string                    `json:"name"`
	Occupancy   PropertyResponseOccupancy `json:"occupancy"`
	Status      PropertyResponseStatus    `json:"status"`
	Type        PropertyResponseType      `json:"type"`
	UpdatedAt   time.Time                 `json:"updated_at"`
}

// PropertyResponseOccupancy defines model for PropertyResponse.Occupancy.
type PropertyResponseOccupancy string

// PropertyResponseStatus defines model for PropertyResponse.Status.
type PropertyResponseStatus string

// PropertyResponseType defines model for PropertyResponse.Type.
type PropertyResponseType string

// PropertyUpdateRequest defines model for PropertyUpdateRequest.
type PropertyUpdateRequest struct {
	Address     *string                      `json:"address,omitempty"`
	Description *string                      `json:"description,omitempty"`
	Name        *string                      `json:"name,omitempty"`
	Status      *PropertyUpdateRequestStatus `json:"status,omitempty"`
	Type        *PropertyUpdateRequestType   `json:"type,omitempty"`
}

// PropertyUpdateRequestStatus defines model for PropertyUpdateRequest.Status.
type PropertyUpdateRequestStatus string

// PropertyUpdateRequestType defines model for PropertyUpdateRequest.Type.
type PropertyUpdateRequestType string

// RecurringOperationCreateRequest defines model for RecurringOperationCreateRequest.
type RecurringOperationCreateRequest struct {
	AmountKopecks int                 `json:"amount_kopecks"`
	Category      OperationCategory   `json:"category"`
	Comment       *string             `json:"comment,omitempty"`
	EndDate       *openapi_types.Date `json:"end_date,omitempty"`
	PaymentDay    int                 `json:"payment_day"`
	StartDate     openapi_types.Date  `json:"start_date"`
	Type          OperationType       `json:"type"`
}

// RecurringOperationResponse defines model for RecurringOperationResponse.
type RecurringOperationResponse struct {
	AmountKopecks int                                   `json:"amount_kopecks"`
	Category      OperationCategory                     `json:"category"`
	Comment       *string                               `json:"comment"`
	CreatedAt     time.Time                             `json:"created_at"`
	EndDate       *openapi_types.Date                   `json:"end_date"`
	Id            openapi_types.UUID                    `json:"id"`
	LeaseId       *openapi_types.UUID                   `json:"lease_id"`
	OwnerId       openapi_types.UUID                    `json:"owner_id"`
	PaymentDay    int                                   `json:"payment_day"`
	Periodicity   RecurringOperationResponsePeriodicity `json:"periodicity"`
	PropertyId    openapi_types.UUID                    `json:"property_id"`
	StartDate     openapi_types.Date                    `json:"start_date"`
	Status        RecurringOperationResponseStatus      `json:"status"`
	Type          OperationType                         `json:"type"`
	UpdatedAt     time.Time                             `json:"updated_at"`
}

// RecurringOperationResponsePeriodicity defines model for RecurringOperationResponse.Periodicity.
type RecurringOperationResponsePeriodicity string

// RecurringOperationResponseStatus defines model for RecurringOperationResponse.Status.
type RecurringOperationResponseStatus string

// RecurringOperationUpdateRequest defines model for RecurringOperationUpdateRequest.
type RecurringOperationUpdateRequest struct {
	AmountKopecks *int                `json:"amount_kopecks,omitempty"`
	Category      *OperationCategory  `json:"category,omitempty"`
	Comment       *string             `json:"comment,omitempty"`
	EndDate       *openapi_types.Date `json:"end_date,omitempty"`
	PaymentDay    *int                `json:"payment_day,omitempty"`
	StartDate     *openapi_types.Date `json:"start_date,omitempty"`
	Type          *OperationType      `json:"type,omitempty"`
}

// RecurringOperationsResponse defines model for RecurringOperationsResponse.
type RecurringOperationsResponse struct {
	Items []RecurringOperationResponse `json:"items"`
}

// ReminderCreateRequest defines model for ReminderCreateRequest.
type ReminderCreateRequest struct {
	ReminderDate openapi_types.Date `json:"reminder_date"`
}

// ReminderResponse defines model for ReminderResponse.
type ReminderResponse struct {
	CreatedAt            time.Time                  `json:"created_at"`
	EventType            ReminderResponseEventType  `json:"event_type"`
	FailedAttempts       int                        `json:"failed_attempts"`
	Id                   openapi_types.UUID         `json:"id"`
	LeaseId              *openapi_types.UUID        `json:"lease_id"`
	MessageBody          string                     `json:"message_body"`
	MessageTitle         string                     `json:"message_title"`
	NextAttemptAt        *time.Time                 `json:"next_attempt_at"`
	OperationId          *openapi_types.UUID        `json:"operation_id"`
	OwnerId              openapi_types.UUID         `json:"owner_id"`
	PropertyId           *openapi_types.UUID        `json:"property_id"`
	RecurringOperationId *openapi_types.UUID        `json:"recurring_operation_id"`
	ScheduledAt          time.Time                  `json:"scheduled_at"`
	SentAt               *time.Time                 `json:"sent_at"`
	Status               ReminderResponseStatus     `json:"status"`
	TargetType           ReminderResponseTargetType `json:"target_type"`
	UpdatedAt            time.Time                  `json:"updated_at"`
}

// ReminderResponseEventType defines model for ReminderResponse.EventType.
type ReminderResponseEventType string

// ReminderResponseStatus defines model for ReminderResponse.Status.
type ReminderResponseStatus string

// ReminderResponseTargetType defines model for ReminderResponse.TargetType.
type ReminderResponseTargetType string

// ReminderUpdateRequest defines model for ReminderUpdateRequest.
type ReminderUpdateRequest struct {
	ReminderDate openapi_types.Date `json:"reminder_date"`
}

// RemindersResponse defines model for RemindersResponse.
type RemindersResponse struct {
	Items []ReminderResponse `json:"items"`
}

// SendPhoneCodeRequest defines model for SendPhoneCodeRequest.
type SendPhoneCodeRequest struct {
	Phone string `json:"phone"`
}

// TenantContactCreateRequest defines model for TenantContactCreateRequest.
type TenantContactCreateRequest struct {
	Comment    *string `json:"comment,omitempty"`
	Email      *string `json:"email,omitempty"`
	Name       string  `json:"name"`
	Patronymic *string `json:"patronymic,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	Surname    *string `json:"surname,omitempty"`
}

// TenantContactResponse defines model for TenantContactResponse.
type TenantContactResponse struct {
	Comment    *string            `json:"comment"`
	CreatedAt  time.Time          `json:"created_at"`
	Email      *string            `json:"email"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	OwnerId    openapi_types.UUID `json:"owner_id"`
	Patronymic *string            `json:"patronymic"`
	Phone      *string            `json:"phone"`
	Surname    *string            `json:"surname"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

// TenantContactUpdateRequest defines model for TenantContactUpdateRequest.
type TenantContactUpdateRequest struct {
	Comment    *string `json:"comment,omitempty"`
	Email      *string `json:"email,omitempty"`
	Name       *string `json:"name,omitempty"`
	Patronymic *string `json:"patronymic,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	Surname    *string `json:"surname,omitempty"`
}

// TenantContactsResponse defines model for TenantContactsResponse.
type TenantContactsResponse struct {
	Items []TenantContactResponse `json:"items"`
}

// VerifyPhoneCodeRequest defines model for VerifyPhoneCodeRequest.
type VerifyPhoneCodeRequest struct {
	Code  string `json:"code"`
	Phone string `json:"phone"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// Conflict defines model for Conflict.
type Conflict = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// ListRemindersParams defines parameters for ListReminders.
type ListRemindersParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SendPhoneCodeJSONRequestBody defines body for SendPhoneCode for application/json ContentType.
type SendPhoneCodeJSONRequestBody = SendPhoneCodeRequest

// VerifyPhoneCodeJSONRequestBody defines body for VerifyPhoneCode for application/json ContentType.
type VerifyPhoneCodeJSONRequestBody = VerifyPhoneCodeRequest

// CreateLeaseJSONRequestBody defines body for CreateLease for application/json ContentType.
type CreateLeaseJSONRequestBody = LeaseCreateRequest

// UpdateLeaseJSONRequestBody defines body for UpdateLease for application/json ContentType.
type UpdateLeaseJSONRequestBody = LeaseUpdateRequest

// UpdateOperationJSONRequestBody defines body for UpdateOperation for application/json ContentType.
type UpdateOperationJSONRequestBody = OperationUpdateRequest

// CreatePropertyJSONRequestBody defines body for CreateProperty for application/json ContentType.
type CreatePropertyJSONRequestBody = PropertyCreateRequest

// UpdatePropertyJSONRequestBody defines body for UpdateProperty for application/json ContentType.
type UpdatePropertyJSONRequestBody = PropertyUpdateRequest

// CreateOperationJSONRequestBody defines body for CreateOperation for application/json ContentType.
type CreateOperationJSONRequestBody = OperationCreateRequest

// CreateOperationReminderJSONRequestBody defines body for CreateOperationReminder for application/json ContentType.
type CreateOperationReminderJSONRequestBody = ReminderCreateRequest

// CreateRecurringOperationJSONRequestBody defines body for CreateRecurringOperation for application/json ContentType.
type CreateRecurringOperationJSONRequestBody = RecurringOperationCreateRequest

// CreateRecurringOperationReminderJSONRequestBody defines body for CreateRecurringOperationReminder for application/json ContentType.
type CreateRecurringOperationReminderJSONRequestBody = ReminderCreateRequest

// UpdateRecurringOperationJSONRequestBody defines body for UpdateRecurringOperation for application/json ContentType.
type UpdateRecurringOperationJSONRequestBody = RecurringOperationUpdateRequest

// UpdateReminderJSONRequestBody defines body for UpdateReminder for application/json ContentType.
type UpdateReminderJSONRequestBody = ReminderUpdateRequest

// CreateTenantContactJSONRequestBody defines body for CreateTenantContact for application/json ContentType.
type CreateTenantContactJSONRequestBody = TenantContactCreateRequest

// UpdateTenantContactJSONRequestBody defines body for UpdateTenantContact for application/json ContentType.
type UpdateTenantContactJSONRequestBody = TenantContactUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (POST /auth/phone/send)
	SendPhoneCode(w http.ResponseWriter, r *http.Request)

	// (POST /auth/phone/verify)
	VerifyPhoneCode(w http.ResponseWriter, r *http.Request)

	// (GET /leases)
	ListLeases(w http.ResponseWriter, r *http.Request)

	// (POST /leases)
	CreateLease(w http.ResponseWriter, r *http.Request)

	// (GET /leases/{id})
	GetLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /leases/{id})
	UpdateLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /leases/{id}/complete)
	CompleteLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /leases/{leaseId}/reminders)
	ListLeaseReminders(w http.ResponseWriter, r *http.Request, leaseId openapi_types.UUID)

	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (DELETE /operations/{id})
	DeleteOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /operations/{id})
	GetOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /operations/{id})
	UpdateOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /properties)
	ListProperties(w http.ResponseWriter, r *http.Request)

	// (POST /properties)
	CreateProperty(w http.ResponseWriter, r *http.Request)

	// (GET /properties/{id})
	GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /properties/{id})
	UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /properties/{id}/archive)
	ArchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /properties/{id}/unarchive)
	UnarchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /properties/{propertyId}/operations)
	ListOperationsByProperty(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID)

	// (POST /properties/{propertyId}/operations)
	CreateOperation(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID)

	// (GET /properties/{propertyId}/operations/{operationId}/reminders)
	ListOperationReminders(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID, operationId openapi_types.UUID)

	// (POST /properties/{propertyId}/operations/{operationId}/reminders)
	CreateOperationReminder(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID, operationId openapi_types.UUID)

	// (GET /properties/{propertyId}/recurring-operations)
	ListRecurringOperationsByProperty(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID)

	// (POST /properties/{propertyId}/recurring-operations)
	CreateRecurringOperation(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID)

	// (GET /properties/{propertyId}/recurring-operations/{recurringOperationId}/reminders)
	ListRecurringOperationReminders(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID, recurringOperationId openapi_types.UUID)

	// (POST /properties/{propertyId}/recurring-operations/{recurringOperationId}/reminders)
	CreateRecurringOperationReminder(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID, recurringOperationId openapi_types.UUID)

	// (GET /recurring-operations/{id})
	GetRecurringOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /recurring-operations/{id})
	UpdateRecurringOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /recurring-operations/{id}/pause)
	PauseRecurringOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /recurring-operations/{id}/resume)
	ResumeRecurringOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /reminders)
	ListReminders(w http.ResponseWriter, r *http.Request, params ListRemindersParams)

	// (DELETE /reminders/{reminderId})
	DeleteReminder(w http.ResponseWriter, r *http.Request, reminderId openapi_types.UUID)

	// (PATCH /reminders/{reminderId})
	UpdateReminder(w http.ResponseWriter, r *http.Request, reminderId openapi_types.UUID)

	// (GET /tenant-contacts)
	ListTenantContacts(w http.ResponseWriter, r *http.Request)

	// (POST /tenant-contacts)
	CreateTenantContact(w http.ResponseWriter, r *http.Request)

	// (GET /tenant-contacts/{id})
	GetTenantContact(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /tenant-contacts/{id})
	UpdateTenantContact(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/phone/send)
func (_ Unimplemented) SendPhoneCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/phone/verify)
func (_ Unimplemented) VerifyPhoneCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /leases)
func (_ Unimplemented) ListLeases(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /leases)
func (_ Unimplemented) CreateLease(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /leases/{id})
func (_ Unimplemented) GetLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /leases/{id})
func (_ Unimplemented) UpdateLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /leases/{id}/complete)
func (_ Unimplemented) CompleteLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /leases/{leaseId}/reminders)
func (_ Unimplemented) ListLeaseReminders(w http.ResponseWriter, r *http.Request, leaseId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /operations/{id})
func (_ Unimplemented) DeleteOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /operations/{id})
func (_ Unimplemented) GetOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /operations/{id})
func (_ Unimplemented) UpdateOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties)
func (_ Unimplemented) ListProperties(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties)
func (_ Unimplemented) CreateProperty(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties/{id})
func (_ Unimplemented) GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /properties/{id})
func (_ Unimplemented) UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{id}/archive)
func (_ Unimplemented) ArchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{id}/unarchive)
func (_ Unimplemented) UnarchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties/{propertyId}/operations)
func (_ Unimplemented) ListOperationsByProperty(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{propertyId}/operations)
func (_ Unimplemented) CreateOperation(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties/{propertyId}/operations/{operationId}/reminders)
func (_ Unimplemented) ListOperationReminders(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID, operationId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{propertyId}/operations/{operationId}/reminders)
func (_ Unimplemented) CreateOperationReminder(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID, operationId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties/{propertyId}/recurring-operations)
func (_ Unimplemented) ListRecurringOperationsByProperty(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{propertyId}/recurring-operations)
func (_ Unimplemented) CreateRecurringOperation(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties/{propertyId}/recurring-operations/{recurringOperationId}/reminders)
func (_ Unimplemented) ListRecurringOperationReminders(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID, recurringOperationId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{propertyId}/recurring-operations/{recurringOperationId}/reminders)
func (_ Unimplemented) CreateRecurringOperationReminder(w http.ResponseWriter, r *http.Request, propertyId openapi_types.UUID, recurringOperationId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /recurring-operations/{id})
func (_ Unimplemented) GetRecurringOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /recurring-operations/{id})
func (_ Unimplemented) UpdateRecurringOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /recurring-operations/{id}/pause)
func (_ Unimplemented) PauseRecurringOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /recurring-operations/{id}/resume)
func (_ Unimplemented) ResumeRecurringOperation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /reminders)
func (_ Unimplemented) ListReminders(w http.ResponseWriter, r *http.Request, params ListRemindersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /reminders/{reminderId})
func (_ Unimplemented) DeleteReminder(w http.ResponseWriter, r *http.Request, reminderId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /reminders/{reminderId})
func (_ Unimplemented) UpdateReminder(w http.ResponseWriter, r *http.Request, reminderId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /tenant-contacts)
func (_ Unimplemented) ListTenantContacts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /tenant-contacts)
func (_ Unimplemented) CreateTenantContact(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /tenant-contacts/{id})
func (_ Unimplemented) GetTenantContact(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /tenant-contacts/{id})
func (_ Unimplemented) UpdateTenantContact(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendPhoneCode operation middleware
func (siw *ServerInterfaceWrapper) SendPhoneCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendPhoneCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyPhoneCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyPhoneCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyPhoneCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLeases operation middleware
func (siw *ServerInterfaceWrapper) ListLeases(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLeases(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLease operation middleware
func (siw *ServerInterfaceWrapper) CreateLease(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLease(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLease operation middleware
func (siw *ServerInterfaceWrapper) GetLease(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLease(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLease operation middleware
func (siw *ServerInterfaceWrapper) UpdateLease(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLease(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteLease operation middleware
func (siw *ServerInterfaceWrapper) CompleteLease(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteLease(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLeaseReminders operation middleware
func (siw *ServerInterfaceWrapper) ListLeaseReminders(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "leaseId" -------------
	var leaseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "leaseId", chi.URLParam(r, "leaseId"), &leaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "leaseId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLeaseReminders(w, r, leaseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOperation operation middleware
func (siw *ServerInterfaceWrapper) DeleteOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOperation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOperation operation middleware
func (siw *ServerInterfaceWrapper) UpdateOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOperation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProperties operation middleware
func (siw *ServerInterfaceWrapper) ListProperties(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProperties(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProperty operation middleware
func (siw *ServerInterfaceWrapper) CreateProperty(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProperty(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProperty operation middleware
func (siw *ServerInterfaceWrapper) GetProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProperty operation middleware
func (siw *ServerInterfaceWrapper) UpdateProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveProperty operation middleware
func (siw *ServerInterfaceWrapper) ArchiveProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnarchiveProperty operation middleware
func (siw *ServerInterfaceWrapper) UnarchiveProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnarchiveProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOperationsByProperty operation middleware
func (siw *ServerInterfaceWrapper) ListOperationsByProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "propertyId", chi.URLParam(r, "propertyId"), &propertyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOperationsByProperty(w, r, propertyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOperation operation middleware
func (siw *ServerInterfaceWrapper) CreateOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "propertyId", chi.URLParam(r, "propertyId"), &propertyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOperation(w, r, propertyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOperationReminders operation middleware
func (siw *ServerInterfaceWrapper) ListOperationReminders(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "propertyId", chi.URLParam(r, "propertyId"), &propertyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	// ------------- Path parameter "operationId" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operationId", chi.URLParam(r, "operationId"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOperationReminders(w, r, propertyId, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOperationReminder operation middleware
func (siw *ServerInterfaceWrapper) CreateOperationReminder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "propertyId", chi.URLParam(r, "propertyId"), &propertyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	// ------------- Path parameter "operationId" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operationId", chi.URLParam(r, "operationId"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOperationReminder(w, r, propertyId, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecurringOperationsByProperty operation middleware
func (siw *ServerInterfaceWrapper) ListRecurringOperationsByProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "propertyId", chi.URLParam(r, "propertyId"), &propertyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecurringOperationsByProperty(w, r, propertyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecurringOperation operation middleware
func (siw *ServerInterfaceWrapper) CreateRecurringOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "propertyId", chi.URLParam(r, "propertyId"), &propertyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecurringOperation(w, r, propertyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecurringOperationReminders operation middleware
func (siw *ServerInterfaceWrapper) ListRecurringOperationReminders(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "propertyId", chi.URLParam(r, "propertyId"), &propertyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	// ------------- Path parameter "recurringOperationId" -------------
	var recurringOperationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recurringOperationId", chi.URLParam(r, "recurringOperationId"), &recurringOperationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recurringOperationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecurringOperationReminders(w, r, propertyId, recurringOperationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecurringOperationReminder operation middleware
func (siw *ServerInterfaceWrapper) CreateRecurringOperationReminder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "propertyId" -------------
	var propertyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "propertyId", chi.URLParam(r, "propertyId"), &propertyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "propertyId", Err: err})
		return
	}

	// ------------- Path parameter "recurringOperationId" -------------
	var recurringOperationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recurringOperationId", chi.URLParam(r, "recurringOperationId"), &recurringOperationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recurringOperationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecurringOperationReminder(w, r, propertyId, recurringOperationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecurringOperation operation middleware
func (siw *ServerInterfaceWrapper) GetRecurringOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecurringOperation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRecurringOperation operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecurringOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRecurringOperation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PauseRecurringOperation operation middleware
func (siw *ServerInterfaceWrapper) PauseRecurringOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PauseRecurringOperation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeRecurringOperation operation middleware
func (siw *ServerInterfaceWrapper) ResumeRecurringOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeRecurringOperation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListReminders operation middleware
func (siw *ServerInterfaceWrapper) ListReminders(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRemindersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReminders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteReminder operation middleware
func (siw *ServerInterfaceWrapper) DeleteReminder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reminderId" -------------
	var reminderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reminderId", chi.URLParam(r, "reminderId"), &reminderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reminderId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteReminder(w, r, reminderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateReminder operation middleware
func (siw *ServerInterfaceWrapper) UpdateReminder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reminderId" -------------
	var reminderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reminderId", chi.URLParam(r, "reminderId"), &reminderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reminderId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateReminder(w, r, reminderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTenantContacts operation middleware
func (siw *ServerInterfaceWrapper) ListTenantContacts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTenantContacts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTenantContact operation middleware
func (siw *ServerInterfaceWrapper) CreateTenantContact(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTenantContact(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTenantContact operation middleware
func (siw *ServerInterfaceWrapper) GetTenantContact(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTenantContact(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTenantContact operation middleware
func (siw *ServerInterfaceWrapper) UpdateTenantContact(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTenantContact(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/phone/send", wrapper.SendPhoneCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/phone/verify", wrapper.VerifyPhoneCode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leases", wrapper.ListLeases)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/leases", wrapper.CreateLease)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leases/{id}", wrapper.GetLease)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/leases/{id}", wrapper.UpdateLease)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/leases/{id}/complete", wrapper.CompleteLease)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leases/{leaseId}/reminders", wrapper.ListLeaseReminders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/operations/{id}", wrapper.DeleteOperation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/operations/{id}", wrapper.GetOperation)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/operations/{id}", wrapper.UpdateOperation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties", wrapper.ListProperties)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties", wrapper.CreateProperty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties/{id}", wrapper.GetProperty)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/properties/{id}", wrapper.UpdateProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{id}/archive", wrapper.ArchiveProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{id}/unarchive", wrapper.UnarchiveProperty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties/{propertyId}/operations", wrapper.ListOperationsByProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{propertyId}/operations", wrapper.CreateOperation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties/{propertyId}/operations/{operationId}/reminders", wrapper.ListOperationReminders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{propertyId}/operations/{operationId}/reminders", wrapper.CreateOperationReminder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties/{propertyId}/recurring-operations", wrapper.ListRecurringOperationsByProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{propertyId}/recurring-operations", wrapper.CreateRecurringOperation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties/{propertyId}/recurring-operations/{recurringOperationId}/reminders", wrapper.ListRecurringOperationReminders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{propertyId}/recurring-operations/{recurringOperationId}/reminders", wrapper.CreateRecurringOperationReminder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recurring-operations/{id}", wrapper.GetRecurringOperation)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/recurring-operations/{id}", wrapper.UpdateRecurringOperation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/recurring-operations/{id}/pause", wrapper.PauseRecurringOperation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/recurring-operations/{id}/resume", wrapper.ResumeRecurringOperation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/reminders", wrapper.ListReminders)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/reminders/{reminderId}", wrapper.DeleteReminder)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/reminders/{reminderId}", wrapper.UpdateReminder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tenant-contacts", wrapper.ListTenantContacts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tenant-contacts", wrapper.CreateTenantContact)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tenant-contacts/{id}", wrapper.GetTenantContact)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/tenant-contacts/{id}", wrapper.UpdateTenantContact)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW3PbuhH+Kxq0b1UiyTlpT/SWuNOOp8lJJpe+ZDwahFxJOCEBBgQdqxn99w4A3gmS",
	"oExSF/spjgQCi91vr1hQv5DD/IBRoCJEy1+IQxgwGoL6zxvsfoQfEYRC/s9hVABVf+Ig8IiDBWF09mfI",
	"qPwsdLbgY/nXXzms0RL9ZZZNPdPfhrMPnH3zwEf7/X6KXAgdTgI5DVrK1SY8Xm4/RdeMrj3ijLJ0utZ+",
	"iv5g4l8sou4Y6/7BxGStFttP0WfG3mG6izkejrH+Z8YmPqa7hO+hpOMLxZHYMk7+B6MwobCe/Dp+Rk75",
	"FnAI1xywgBwSA84C4IJAzCTfj+nz8f1boBuxRcur+Xw+RWIXAFqiUHBCN0gtHbCQiBX2WUTF6jsLwPmu",
	"pnFhjSNPoOV8inxCiR/56u94CkIFbIDLOYC6KxcLkE+tGfexQEukPjAsGOCdpG7l4l1MoZ75xSK3zMK0",
	"TLzL3Yq4hZWiiLimlbhcprqv5r2EAnNhvxsBFFOxkpDAjrCjTJH2IyJcwulrYVuF9c07KHLwNp2dffsT",
	"tMIqjHyM7VYjPGjkefibB2gpeASG7TkKae4Kiwo3ngniG1lSj6huyGklzhIG7CcFbouZEjoHA+GDgRcK",
	"LCI1FVAJ5q8I/8REELpZqZnQFGFHkDsNI4W2cCU/YRRNlY/zQIAkGXNnS+7AzWGpDt/K5Hne+zVafm02",
	"b5/Vc9f6sRSL+9uyWPdTFAVuR4yVFEgxvqhFqcwrO0g5Z6VqNVgu4qSgJoX91GrnFzXGxoIPpl7doT8U",
	"lA+0oWbOhvWGjwjwi380IbhoRbP1MOd4V8WgmtIk73cNphh8TDwrQ2xpbSj2wWq+AAvO6M4njt3wLaNg",
	"hCNnHuStkNI8aVVcn1CjSQkjbkmmUc8VJfG6Jn6/D4CrgOwaC9gwvstTJyEszYPYSvNAHabMSySIR5RM",
	"5IIBJnIDAt+nI+E+AClA03ay9Zqjsq6BiJMjvwmn1f3up91CQE8i3dafsWS5DvqtPrDcxWc5uCx5NUOO",
	"JVNUMcgluhqRUa+QNtatL8EMEnxZSpGEK7h3IM440l1+Y8wDTNtA0Ur5ASDpFqV1DsKciMv/rDLKDtza",
	"AWDuK8TJBTXFaKe7epQQ0C2CKW4vZ11Tg2plL1tioDFV8VxtZL1oeguDqkbz8FAoqXlUSHJBxIFQ1VLR",
	"UGDq1AQfGjw3rvHbLEWqIkcQ4ZnnTCTRrJCxyulp0qVqNh3vtC+RxDPu+pGImqotdnFdDmFYUpWXNQWl",
	"XC3LRrWSYDA/8uXLBh1JE94Ac+HriI4z5ku7l3wkbd6WRSGgWNG5Q7AnDeF6TRz56U/MIRmxwRxvQKV1",
	"/LtcbYo8TE0ZcYmzivbUACdsauJ0Q+yRMbmnOkxBEA9NKapWznGiAFOnEGCvOUhi1HekpqZgKF0klQof",
	"Sx2lSuHbKhMngIa+PLsZRrlSRcbrbq46QV2brz0J/bbExe3pmoYK/z8mgef5Z4kjFfm71o7GyC0LhcK2",
	"6ntV5Becbo5Rv39YJtpv8R84YS5xiCg4PZ9RsfV2RsvUNVV9+DFAYjMDHIUtvvPMkthaPSxKJuc3u/jK",
	"quJ2zlCfbPUIOW5VTr1lVg22+/Ac6yP4hLrAWzw/j4fZ8rO0fvHxJjoaToYP8QB3Ejvl+CtXAYnkY9qG",
	"w31AeBxDqQ/KB5MmW7XGxFM0CfADYaFmY7gVH8IQb2D1jbk7Y3KUDKivM1C4F8mumjjeodg6io9s9met",
	"i/VYipVa60ZeR8CG6hTzAfyuutwAqKthHeqUQ2NWeTPqgOfVuWHMN9CgPMjIrkR7BsxH88fnORoL2p4/",
	"SM8Looz9krJUFbqrl9ZWrMU3j2ZNe/Q9JfN8uMf5BNT9sGUUrplbz6L0TBfusR9IwKO//ePVq1fz+Xyx",
	"uLpq71tSz5vWLzR/2DerVX2LX1cVtq4pFM+5O5xr506pLUqArVw4XjvWYD0GD821DmtAaDfP1u0FA1jL",
	"uJCX0FDYZta7oEWSxfTdLGABVw9oJDpZ7WrecW8Gt6ZF7WCr+1/gZL1rt7sOc0tmd3H14reXf0cd+m6M",
	"pniqp67SpqIeJ+JE7D7JzWs6QghDmWQy9p2oNQhFS+To/yYgSEat8lqMA/If2OnWZULXTBGoA130mgN1",
	"8eSDh6nUp8nrDzdoiu6Ah7q5ef588Xweh60UBwQt0Yvn8+cvtK5sFWUzHIntzGMbFmn+Mc3HNAS6cdES",
	"vdXfT4st+lfz3/SJYr6j+i3bbMCd6OFbwNJvy1GfQDzL9p81bpe5LTf623xRh6iUgFm1dTvmu2qYLHH8",
	"6+3+Vo7R21UynIWgG+3NWy44dpSef76Js5BeGtONwcO+iLi4c7Od8XKOiQqKFQfn7RzMXbGQj1y9an+k",
	"fE9AyyvP1TulmvV8LanuQJytMRBWvJ33RkWuH9Fw9+B1JLZAhZxaJTAHK0t3UXfXr4fhQyVRamcbMJkX",
	"EgrdUYoGlEapZ9UgET1i4pGD2WRjhqY1mqGjd0XDQFphuNFipRGLfiloFcEkjtHQaPC2dR8ayLNfxN3X",
	"ovnfIBIhBphjH4TS6q+x15euN/P5ytcX+T/N8bKtNft2aH1pl5VuKAoPtyvamTU/lF6Ms9UwLJxtVTQ6",
	"hB9XOgOpcTEbGdmxWUIjzq7QmF6qfzSV9H6WXOipj3Gu4xGPyQxk15xOVHTq3xt3P0sKjhbxSFp5tBJi",
	"vMLJSrJaRzVIM9vyiclRlzDqPO47QEcL5K8jzoGKSRTqU7EB449031kM4kJijIpM+af6/H3uKOMIZsiQ",
	"p6YUTTTl7mlFDnUAOzIj+8Oy4by9Cum8kM4tvBtfUv2HeDV9MSOHeR2hcjnhXrGKXBsjZPcNhnQ+hlsN",
	"BjFko45bv0jaoAcqYZhvUYxcxajeCqmVx+50axkZyFvrGTmhnrXv6yS48/N8o4tpOP0+qt/rBJNL9Hq6",
	"0BHfCaqvc7zWAx6ldUgvTJ24ECPaKsYvyZBHKciUQSctyqQX9Mbd54oAjdFp1rP9ZtdJstlap5/Ehlap",
	"iY6JJ2vGJ8nmTsytN0TU3fLZPoU3YF571Pi9Y147egR/RIsy+5WDoG2tPMfPLvXynqA6NU6ep/KpIH8k",
	"i5XQfmFw6N8umi8ujWwWq23x9Wh8BEYxvQ/yzDLgMtyWu7zIq+lKoBEv8fAJu4hgrLr9C4jK2l6dMLod",
	"qr8aaoWwR2qcZr94hXP2QZyJ6ycTzZk29hTWHd32nU58NwxALjzQswPoBVlTs9VsOfw60OWTc4rhujrY",
	"8zsbO6IUxwjYjnpe9nA8Xc4hWq2JmamXBNWfwnyQXz/Zmio24pcrnY2cOYSR3yDoj+r7J0lXJa05d4Ki",
	"tsufmrOlHxGoV20lzeLEJwLlZZf+CNBiPp9m74ZaqPdONb0dKg2JS0uw9TqEmjVafmjo/POjzsKV2bP+",
	"88amsbpT6pPNPHx/dVahTV+Ic05R2pG4Olymd+TIrENJ//SDMPmAxS3k7Cf1bK2A/l2cZ/Hv4jQb+uIr",
	"Mobs/K15GYfpx/TUyElC/3FbgAtkD9QH3PDeo5GLKTXvNmmT0XGqKmMoT2tBpYyPs456DxX/+VVQjiO2",
	"gU3HUb3zodh5rI5aDeJ3CeIi7qEl2goRLGczjznY27JQLH+f/z5H+9v9/wMAAP//mUjYgV94AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
