// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for LeaseResponseStatus.
const (
	LeaseResponseStatusActive         LeaseResponseStatus = "active"
	LeaseResponseStatusArchived       LeaseResponseStatus = "archived"
	LeaseResponseStatusAwaitingStart  LeaseResponseStatus = "awaiting_start"
	LeaseResponseStatusCompleted      LeaseResponseStatus = "completed"
	LeaseResponseStatusRequiresAction LeaseResponseStatus = "requires_action"
)

// Defines values for MeResponseRole.
const (
	Admin MeResponseRole = "admin"
	Owner MeResponseRole = "owner"
)

// Defines values for PropertyCreateRequestType.
const (
	PropertyCreateRequestTypeApartment  PropertyCreateRequestType = "apartment"
	PropertyCreateRequestTypeApartments PropertyCreateRequestType = "apartments"
	PropertyCreateRequestTypeCommercial PropertyCreateRequestType = "commercial"
	PropertyCreateRequestTypeGarage     PropertyCreateRequestType = "garage"
	PropertyCreateRequestTypeHouse      PropertyCreateRequestType = "house"
	PropertyCreateRequestTypeLand       PropertyCreateRequestType = "land"
	PropertyCreateRequestTypeOffice     PropertyCreateRequestType = "office"
	PropertyCreateRequestTypeParking    PropertyCreateRequestType = "parking"
	PropertyCreateRequestTypeRoom       PropertyCreateRequestType = "room"
	PropertyCreateRequestTypeWarehouse  PropertyCreateRequestType = "warehouse"
)

// Defines values for PropertyResponseOccupancy.
const (
	Free     PropertyResponseOccupancy = "free"
	Occupied PropertyResponseOccupancy = "occupied"
)

// Defines values for PropertyResponseStatus.
const (
	PropertyResponseStatusActive      PropertyResponseStatus = "active"
	PropertyResponseStatusArchived    PropertyResponseStatus = "archived"
	PropertyResponseStatusMaintenance PropertyResponseStatus = "maintenance"
)

// Defines values for PropertyResponseType.
const (
	PropertyResponseTypeApartment  PropertyResponseType = "apartment"
	PropertyResponseTypeApartments PropertyResponseType = "apartments"
	PropertyResponseTypeCommercial PropertyResponseType = "commercial"
	PropertyResponseTypeGarage     PropertyResponseType = "garage"
	PropertyResponseTypeHouse      PropertyResponseType = "house"
	PropertyResponseTypeLand       PropertyResponseType = "land"
	PropertyResponseTypeOffice     PropertyResponseType = "office"
	PropertyResponseTypeParking    PropertyResponseType = "parking"
	PropertyResponseTypeRoom       PropertyResponseType = "room"
	PropertyResponseTypeWarehouse  PropertyResponseType = "warehouse"
)

// Defines values for PropertyUpdateRequestStatus.
const (
	Active      PropertyUpdateRequestStatus = "active"
	Maintenance PropertyUpdateRequestStatus = "maintenance"
)

// Defines values for PropertyUpdateRequestType.
const (
	Apartment  PropertyUpdateRequestType = "apartment"
	Apartments PropertyUpdateRequestType = "apartments"
	Commercial PropertyUpdateRequestType = "commercial"
	Garage     PropertyUpdateRequestType = "garage"
	House      PropertyUpdateRequestType = "house"
	Land       PropertyUpdateRequestType = "land"
	Office     PropertyUpdateRequestType = "office"
	Parking    PropertyUpdateRequestType = "parking"
	Room       PropertyUpdateRequestType = "room"
	Warehouse  PropertyUpdateRequestType = "warehouse"
)

// LeaseCreateRequest defines model for LeaseCreateRequest.
type LeaseCreateRequest struct {
	Comment              *string             `json:"comment,omitempty"`
	DepositAmountKopecks *int                `json:"deposit_amount_kopecks,omitempty"`
	EndDate              *openapi_types.Date `json:"end_date,omitempty"`
	PaymentDay           int                 `json:"payment_day"`
	PropertyId           openapi_types.UUID  `json:"property_id"`
	RentAmountKopecks    int                 `json:"rent_amount_kopecks"`
	StartDate            openapi_types.Date  `json:"start_date"`
	TenantContactId      *openapi_types.UUID `json:"tenant_contact_id,omitempty"`
}

// LeaseResponse defines model for LeaseResponse.
type LeaseResponse struct {
	Comment              *string                `json:"comment"`
	CreatedAt            time.Time              `json:"created_at"`
	DepositAmountKopecks int                    `json:"deposit_amount_kopecks"`
	EndDate              *openapi_types.Date    `json:"end_date"`
	Id                   openapi_types.UUID     `json:"id"`
	OwnerId              openapi_types.UUID     `json:"owner_id"`
	PaymentDay           int                    `json:"payment_day"`
	PropertyId           openapi_types.UUID     `json:"property_id"`
	RentAmountKopecks    int                    `json:"rent_amount_kopecks"`
	StartDate            openapi_types.Date     `json:"start_date"`
	Status               LeaseResponseStatus    `json:"status"`
	TenantContact        *TenantContactResponse `json:"tenant_contact"`
	UpdatedAt            time.Time              `json:"updated_at"`
}

// LeaseResponseStatus defines model for LeaseResponse.Status.
type LeaseResponseStatus string

// LeaseUpdateRequest defines model for LeaseUpdateRequest.
type LeaseUpdateRequest struct {
	Comment              *string             `json:"comment,omitempty"`
	DepositAmountKopecks *int                `json:"deposit_amount_kopecks,omitempty"`
	EndDate              *openapi_types.Date `json:"end_date,omitempty"`
	PaymentDay           *int                `json:"payment_day,omitempty"`
	RentAmountKopecks    *int                `json:"rent_amount_kopecks,omitempty"`
	StartDate            *openapi_types.Date `json:"start_date,omitempty"`
	TenantContactId      *openapi_types.UUID `json:"tenant_contact_id,omitempty"`
}

// LeasesResponse defines model for LeasesResponse.
type LeasesResponse struct {
	Items []LeaseResponse `json:"items"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Email      *string            `json:"email"`
	Id         openapi_types.UUID `json:"id"`
	Name       *string            `json:"name"`
	Patronymic *string            `json:"patronymic"`
	Phone      string             `json:"phone"`
	Role       MeResponseRole     `json:"role"`
	Surname    *string            `json:"surname"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// Problem defines model for Problem.
type Problem struct {
	Detail    *string `json:"detail,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// PropertiesResponse defines model for PropertiesResponse.
type PropertiesResponse struct {
	Items []PropertyResponse `json:"items"`
}

// PropertyCreateRequest defines model for PropertyCreateRequest.
type PropertyCreateRequest struct {
	Address     string                    `json:"address"`
	Description *string                   `json:"description,omitempty"`
	Name        string                    `json:"name"`
	Type        PropertyCreateRequestType `json:"type"`
}

// PropertyCreateRequestType defines model for PropertyCreateRequest.Type.
type PropertyCreateRequestType string

// PropertyResponse defines model for PropertyResponse.
type PropertyResponse struct {
	Address     string                    `json:"address"`
	CreatedAt   time.Time                 `json:"created_at"`
	Description *string                   `json:"description,omitempty"`
	Id          openapi_types.UUID        `json:"id"`
	Name        string                    `json:"name"`
	Occupancy   PropertyResponseOccupancy `json:"occupancy"`
	Status      PropertyResponseStatus    `json:"status"`
	Type        PropertyResponseType      `json:"type"`
	UpdatedAt   time.Time                 `json:"updated_at"`
}

// PropertyResponseOccupancy defines model for PropertyResponse.Occupancy.
type PropertyResponseOccupancy string

// PropertyResponseStatus defines model for PropertyResponse.Status.
type PropertyResponseStatus string

// PropertyResponseType defines model for PropertyResponse.Type.
type PropertyResponseType string

// PropertyUpdateRequest defines model for PropertyUpdateRequest.
type PropertyUpdateRequest struct {
	Address     *string                      `json:"address,omitempty"`
	Description *string                      `json:"description,omitempty"`
	Name        *string                      `json:"name,omitempty"`
	Status      *PropertyUpdateRequestStatus `json:"status,omitempty"`
	Type        *PropertyUpdateRequestType   `json:"type,omitempty"`
}

// PropertyUpdateRequestStatus defines model for PropertyUpdateRequest.Status.
type PropertyUpdateRequestStatus string

// PropertyUpdateRequestType defines model for PropertyUpdateRequest.Type.
type PropertyUpdateRequestType string

// SendPhoneCodeRequest defines model for SendPhoneCodeRequest.
type SendPhoneCodeRequest struct {
	Phone string `json:"phone"`
}

// TenantContactCreateRequest defines model for TenantContactCreateRequest.
type TenantContactCreateRequest struct {
	Comment    *string `json:"comment,omitempty"`
	Email      *string `json:"email,omitempty"`
	Name       string  `json:"name"`
	Patronymic *string `json:"patronymic,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	Surname    *string `json:"surname,omitempty"`
}

// TenantContactResponse defines model for TenantContactResponse.
type TenantContactResponse struct {
	Comment    *string            `json:"comment"`
	CreatedAt  time.Time          `json:"created_at"`
	Email      *string            `json:"email"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	OwnerId    openapi_types.UUID `json:"owner_id"`
	Patronymic *string            `json:"patronymic"`
	Phone      *string            `json:"phone"`
	Surname    *string            `json:"surname"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

// TenantContactsResponse defines model for TenantContactsResponse.
type TenantContactsResponse struct {
	Items []TenantContactResponse `json:"items"`
}

// VerifyPhoneCodeRequest defines model for VerifyPhoneCodeRequest.
type VerifyPhoneCodeRequest struct {
	Code  string `json:"code"`
	Phone string `json:"phone"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// SendPhoneCodeJSONRequestBody defines body for SendPhoneCode for application/json ContentType.
type SendPhoneCodeJSONRequestBody = SendPhoneCodeRequest

// VerifyPhoneCodeJSONRequestBody defines body for VerifyPhoneCode for application/json ContentType.
type VerifyPhoneCodeJSONRequestBody = VerifyPhoneCodeRequest

// CreateLeaseJSONRequestBody defines body for CreateLease for application/json ContentType.
type CreateLeaseJSONRequestBody = LeaseCreateRequest

// UpdateLeaseJSONRequestBody defines body for UpdateLease for application/json ContentType.
type UpdateLeaseJSONRequestBody = LeaseUpdateRequest

// CreatePropertyJSONRequestBody defines body for CreateProperty for application/json ContentType.
type CreatePropertyJSONRequestBody = PropertyCreateRequest

// UpdatePropertyJSONRequestBody defines body for UpdateProperty for application/json ContentType.
type UpdatePropertyJSONRequestBody = PropertyUpdateRequest

// CreateTenantContactJSONRequestBody defines body for CreateTenantContact for application/json ContentType.
type CreateTenantContactJSONRequestBody = TenantContactCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (POST /auth/phone/send)
	SendPhoneCode(w http.ResponseWriter, r *http.Request)

	// (POST /auth/phone/verify)
	VerifyPhoneCode(w http.ResponseWriter, r *http.Request)

	// (GET /leases)
	ListLeases(w http.ResponseWriter, r *http.Request)

	// (POST /leases)
	CreateLease(w http.ResponseWriter, r *http.Request)

	// (GET /leases/{id})
	GetLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /leases/{id})
	UpdateLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /leases/{id}/complete)
	CompleteLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (GET /properties)
	ListProperties(w http.ResponseWriter, r *http.Request)

	// (POST /properties)
	CreateProperty(w http.ResponseWriter, r *http.Request)

	// (GET /properties/{id})
	GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /properties/{id})
	UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /properties/{id}/archive)
	ArchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /properties/{id}/unarchive)
	UnarchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /tenant-contacts)
	ListTenantContacts(w http.ResponseWriter, r *http.Request)

	// (POST /tenant-contacts)
	CreateTenantContact(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/phone/send)
func (_ Unimplemented) SendPhoneCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/phone/verify)
func (_ Unimplemented) VerifyPhoneCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /leases)
func (_ Unimplemented) ListLeases(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /leases)
func (_ Unimplemented) CreateLease(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /leases/{id})
func (_ Unimplemented) GetLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /leases/{id})
func (_ Unimplemented) UpdateLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /leases/{id}/complete)
func (_ Unimplemented) CompleteLease(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties)
func (_ Unimplemented) ListProperties(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties)
func (_ Unimplemented) CreateProperty(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /properties/{id})
func (_ Unimplemented) GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /properties/{id})
func (_ Unimplemented) UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{id}/archive)
func (_ Unimplemented) ArchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /properties/{id}/unarchive)
func (_ Unimplemented) UnarchiveProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /tenant-contacts)
func (_ Unimplemented) ListTenantContacts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /tenant-contacts)
func (_ Unimplemented) CreateTenantContact(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendPhoneCode operation middleware
func (siw *ServerInterfaceWrapper) SendPhoneCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendPhoneCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyPhoneCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyPhoneCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyPhoneCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLeases operation middleware
func (siw *ServerInterfaceWrapper) ListLeases(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLeases(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLease operation middleware
func (siw *ServerInterfaceWrapper) CreateLease(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLease(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLease operation middleware
func (siw *ServerInterfaceWrapper) GetLease(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLease(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLease operation middleware
func (siw *ServerInterfaceWrapper) UpdateLease(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLease(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteLease operation middleware
func (siw *ServerInterfaceWrapper) CompleteLease(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteLease(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProperties operation middleware
func (siw *ServerInterfaceWrapper) ListProperties(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProperties(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProperty operation middleware
func (siw *ServerInterfaceWrapper) CreateProperty(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProperty(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProperty operation middleware
func (siw *ServerInterfaceWrapper) GetProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProperty operation middleware
func (siw *ServerInterfaceWrapper) UpdateProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveProperty operation middleware
func (siw *ServerInterfaceWrapper) ArchiveProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnarchiveProperty operation middleware
func (siw *ServerInterfaceWrapper) UnarchiveProperty(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnarchiveProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTenantContacts operation middleware
func (siw *ServerInterfaceWrapper) ListTenantContacts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTenantContacts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTenantContact operation middleware
func (siw *ServerInterfaceWrapper) CreateTenantContact(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTenantContact(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/phone/send", wrapper.SendPhoneCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/phone/verify", wrapper.VerifyPhoneCode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leases", wrapper.ListLeases)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/leases", wrapper.CreateLease)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leases/{id}", wrapper.GetLease)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/leases/{id}", wrapper.UpdateLease)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/leases/{id}/complete", wrapper.CompleteLease)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties", wrapper.ListProperties)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties", wrapper.CreateProperty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/properties/{id}", wrapper.GetProperty)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/properties/{id}", wrapper.UpdateProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{id}/archive", wrapper.ArchiveProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/properties/{id}/unarchive", wrapper.UnarchiveProperty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tenant-contacts", wrapper.ListTenantContacts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tenant-contacts", wrapper.CreateTenantContact)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Ra3XLbNhN9FQ2+766MRdlxG/PO8Uw7mTqpJz+98Xg0CLkSEZMAA4BOWI/evQOApPgD",
	"ipQsykpzJ4kgsHv27OJgoUfkszhhFKgUyHtEHETCqAD95TUO3sPXFIRU33xGJVD9ESdJRHwsCaPTL4JR",
	"9ZvwQ4ix+vR/Dgvkof9N11NPzVMxveHscwQxWq1WDgpA+JwkahrkqdUmPF9u5aB3TP7OUhocYul3TE4W",
	"erGVgz4y9hbTLPdcHGL9j4xNYkyzwn+h7PhEcSpDxsk/cBAQauupx/k7asprwAKuOGAJFUYknCXAJYEc",
	"pDjO7Yvx92ugSxki79R1XQfJLAHkISE5oUukl06YIHKOY5ZSOb9nCfj3epoAFjiNJPJcB8WEkjiN9ed8",
	"CkIlLIGrOYAG8wBLUG8tGI+xRB7SP1gWTHCmrJsHOMstNDOfzSrLzGzL5F5mcxLUVkpTEthW4mqZtl+b",
	"fRESczncGwkUUzlXlMC+HGaZNu1rSrii023Nrdr6dg/qCN6Vs7PPX8DXCas58j6vHxvpQdMowp8jQJ7k",
	"KVjc8zXTgjmWLTReSBJbIelm1HbM6TVuIA3YNwp8KGca7ByNhE8mnpBYpnoqoIrMtwh/w0QSupzrmZCD",
	"sC/Jg6GRZpuYq18YRY7eayKQoEzG3A/JAwQVLnXxW5e8KPprgbzbzeXto37vyrxWcnF11wzrykFpEmzJ",
	"sUYCaeDrWVTGvOVBidygVOvgcp0ntTSp+dOZnZ/0mCEVfLT02p76Y1F5xxpqR1Z0Fz4iIa5/2MTgehVd",
	"r4c5x1mbg3pKW7zfbijFEGMSDSrEA6sNxTEMmi/BkjOaxcQfNjxkFKx05CyCahXSmaeqShATai0pIuUD",
	"zbTmubYkX9eGdyGsWmAHIHO02+hSITH1Ozw0WfomsD5d1+F2HkgiI/uc5ofHHof102KacqkOp3NP90X/",
	"fMZsDxlQTNUjW3EQcBCiIVvPO1RrRTAPkbkF46ojz8+d7siUu2qCudTFWHGOxYraxU9qIwhZKsDsqDFw",
	"n+BIbT+LBfHVr98wh2LEEnO8BL138Hu1moMiTG3bbgNZbbtTsKGAaRPS3SSogLwnsVcLxFPrVlu8+X6a",
	"YOpn1ZgsOChj9DPSIVws+qiQQzFWOUp1wvfJnyNgw74Ukp1GFT20xno7RVOwrkfUHEd+D+TF3fGWhhb+",
	"H4AGN2pbvGJBN/zlFg7fsRL/yEO//HZxceG67mx2etp/TNXv2+Jf0/rDexMtfEs1tHt067JmCxlTESUD",
	"inEvCs93+h5NUj71XL2b3uwdOVxN7quOVs6WeUktbKi5uZaqJiROGfrtqmuNV3uTdx3n85013t/AySLr",
	"r0I+CxpFaHZ69vL8V7TFocNamBwzdds2xRHwU05k9kE5b+wQIARh9Iqxe6LXIBR5yDdfC9IXo+ZVTuOE",
	"/AmZ6dsSumDaQCP00SUHGuDJTYSpYtfk8uYNctADcGE6u+7J7MTVuZMAxQlBHjo7cU/ODHNCbdkUpzKc",
	"RmzJUoMfMzgqFHWjWR1E0LV57tTvCU7dl+akU20nX7PlEoKJGR4CDoDrwR9Avlj7v+5aN9FWjr50Z12M",
	"Kg2YtvvWOe66W9RA/PZudafGGHd1DKcCzC2D3eXaNofKc9lrFmR768pbt9JVnXF526ofeDXHRCibNIJu",
	"P4KVex71yulF/yvNSxITryqqDzo1u3FtpO5IyHYUiEHYunuzotKMsVy8XKYyBCrV1LozunOybB/q7fPr",
	"afyIdK9Mvb4EW3khQpp2GhoxGo2GnSUiZsQkIjvDNKQMOR2ZYbSstmGkrLBc5w3KiNl+LegNwSRXLOhg",
	"9B66fRgiTx9JsOpk8x8giyAmmOMYpM7q23zXV1vves/Xe30df6eCZV9f+m7sfOmPlWl0it3ritnMNr9U",
	"/itgaIZh6Yft0JiewWGjM1Ia19sfB97YBlIjP2ugQ+5S+2dTI++nxW1mt8a5ykf8TGVgfcd7ZKEzp/Wu",
	"Sv0W0LMJwKuUc6BykgpzgTPivlU/FneKsPXFzpioWK6PLOisRz2vICv6zSNpMvt11YFlWfv6rTMe2fGK",
	"szXJewVaJag/dHHeKnA/nlI7eJjGy+9n1Wtb0eS/o9oaBWGaX752C7dLM+CnrA7lzfSRBzGlvWH8VAz5",
	"KQNZAnR0oTR/vXuR//VusxStX0SNKUc7rrxs/9fXIyeF/c+rS2tmjyRON9y1H1ihdtwg9sXoSMWqHsQf",
	"imKU8gh5KJQy8abTiPk4CpmQ3iv3lYtWd6t/AwAA//9t8SjQrTMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
