// Code generated by tools/payment-categories/generate.mjs from catalog.json. DO NOT EDIT.
//
// zz_categories.gen.go — сгенерировано из tools/payment-categories/catalog.json.
// НЕ редактировать вручную. Чтобы регенерировать:
//
//	cd tools/payment-categories && node generate.mjs
//
// (или из корня монорепо: make categories-gen)
//
// Самодостаточный модуль без импортов: словарь дефолтного каталога категорий
// платежей для бекенда — слаг (каноническая ссылка из БД) → название (снапшот
// в операцию при материализации). UI-метаданные каталога (иконка, цвет
// подложки, порядок UI) — только во фронтенд-артефакте генератора
// (features/payment-categories/lib/generated/categories.ts). Категория
// нейтральна к направлению: доход/расход выбирается на платеже, а не в каталоге.

package domain

// CategoryCatalogEntry — запись словаря дефолтного каталога категорий
// платежей: слаг — каноническая ссылка из БД, название — источник снапшота
// category_label при материализации операции.
type CategoryCatalogEntry struct {
	Slug  string
	Label string
}

// defaultCategories — словарь дефолтного каталога. Общий для всех вызовов:
// не мутировать.
var defaultCategories = []CategoryCatalogEntry{
	{Slug: "rent", Label: "Арендная плата"},
	{Slug: "utilities", Label: "Коммунальные услуги"},
	{Slug: "electricity", Label: "Электроэнергия"},
	{Slug: "water-supply", Label: "Водоснабжение"},
	{Slug: "sewerage", Label: "Канализация"},
	{Slug: "heating", Label: "Отопление"},
	{Slug: "gas", Label: "Газ"},
	{Slug: "garbage-removal", Label: "Вывоз мусора"},
	{Slug: "utilities-compensation", Label: "Компенсация коммунальных услуг"},
	{Slug: "mortgage", Label: "Ипотека"},
	{Slug: "loan", Label: "Кредит"},
	{Slug: "bank-fees", Label: "Услуги банка"},
	{Slug: "insurance", Label: "Страхование"},
	{Slug: "taxes", Label: "Налоги"},
	{Slug: "legal-services", Label: "Юридические услуги"},
	{Slug: "notary-services", Label: "Нотариальные услуги"},
	{Slug: "deposit", Label: "Залог"},
	{Slug: "commission", Label: "Комиссия"},
	{Slug: "advertising", Label: "Реклама"},
	{Slug: "repairs", Label: "Ремонт"},
	{Slug: "capital-repairs", Label: "Капитальный ремонт"},
	{Slug: "capital-repairs-fee", Label: "Взнос на капитальный ремонт"},
	{Slug: "cleaning", Label: "Клининг"},
	{Slug: "misc-services", Label: "Различные услуги"},
	{Slug: "internet", Label: "Интернет"},
	{Slug: "tv", Label: "Телевидение"},
	{Slug: "furniture", Label: "Мебель"},
	{Slug: "appliances", Label: "Техника"},
	{Slug: "equipment", Label: "Оборудование"},
	{Slug: "security", Label: "Охрана"},
	{Slug: "concierge", Label: "Консьерж"},
	{Slug: "parking", Label: "Парковка"},
	{Slug: "management-company", Label: "Управляющая компания"},
	{Slug: "grounds-maintenance", Label: "Обслуживание территории"},
	{Slug: "intercom", Label: "Домофон"},
	{Slug: "landscaping", Label: "Благоустройство"},
	{Slug: "damage-compensation", Label: "Возмещение ущерба"},
	{Slug: "penalty", Label: "Неустойка"},
	{Slug: "late-fees", Label: "Пени"},
	{Slug: "fines", Label: "Штрафы"},
}

// CategoryBySlug ищет запись дефолтного каталога по слагу.
func CategoryBySlug(slug string) (CategoryCatalogEntry, bool) {
	for _, entry := range defaultCategories {
		if entry.Slug == slug {
			return entry, true
		}
	}
	return CategoryCatalogEntry{}, false
}

// CategoryCatalogEntries возвращает все записи дефолтного каталога в
// порядке каталога. Слайс общий для всех вызовов: не мутировать.
func CategoryCatalogEntries() []CategoryCatalogEntry {
	return defaultCategories
}

// IsValidDefaultCategorySlug сообщает, входит ли слаг в дефолтный каталог.
func IsValidDefaultCategorySlug(slug string) bool {
	_, ok := CategoryBySlug(slug)
	return ok
}
