#!/usr/bin/env node
// Domain rules for db migrations (wave 3, #309; decision #295) — the two
// invariants Squawk does not know about:
//
//   money-float-type — money is BIGINT kopecks; numeric/decimal/real/double/
//     float column types are banned in migrations outright (money columns are
//     structurally indistinguishable, so the ban is total;
//     docs/adr/0036-fintech-domain-language.md).
//   id-column-default — id columns get no DEFAULT: ids are UUIDv7 generated
//     by the application, not the database (ADR 0019; a genuine non-money
//     decimal column or an id default would need a recorded exclusion here).
//
// Statement-aware parsing: comments, string literals and dollar-quoted bodies
// are respected — a plain grep was rejected by the research
// (docs/research/2026-08-16-migration-lint-and-arch-tools.md).
//
// Scope: down migrations (.down.sql) are skipped — they are deliberate
// inverses of linted up migrations (rolling back ADR 0019 restores id
// defaults, rolling back the kopecks migration restores NUMERIC — by
// construction). Historical up migrations that predate the rules are exempted
// point-wise below with reasons; no baseline file (decision #295).
//
// Contract: `node domain-rules.mjs <migration.sql>...` → exit 0 (clean),
// 1 (findings printed to stdout), 2 (usage/IO error).

import { readFileSync } from "node:fs";

const RULE_MONEY = "money-float-type";
const RULE_ID = "id-column-default";

// Historical migrations applied before the rules existed; each entry keeps its
// reason so the list stays a set of deliberate exclusions, not a baseline.
const HISTORICAL_EXEMPT = new Map([
  ["000001_init_schema.up.sql", "pre-kopecks NUMERIC prices (converted by 000022) and pre-ADR-0019 id DEFAULTs (dropped by 000079)"],
  ["000002_properties.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
  ["000003_leases.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
  ["000008_notifications.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
  ["000024_payment_methods.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
  ["000038_property_photos.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
  ["000055_login_codes.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
  ["000057_sent_email_reminders.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
  ["000076_operation_categories.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
  ["000087_property_contacts.up.sql", "pre-ADR-0019 id DEFAULT gen_random_uuid() (dropped by 000079)"],
]);

// All transforms below are length- and newline-preserving, so offsets in the
// cleaned text map 1:1 onto lines of the original file.

const DOLLAR_TAG = /\$[A-Za-z0-9_]*\$/y;

// Detects a dollar-quote opening tag ($$, $tag$) at the given offset; returns
// the tag string or null.
function dollarTagAt(text, i) {
  DOLLAR_TAG.lastIndex = i;
  return DOLLAR_TAG.exec(text)?.[0] ?? null;
}

const ID_DEFAULT_MESSAGE = "id column must have no DEFAULT — ids are UUIDv7 generated by the application (ADR 0019)";

function finding(rule, line, message) {
  return { rule, line, message };
}

// Blanks `--` line comments and `/* */` block comments (newlines kept) while
// respecting string literals and dollar-quoted bodies.
function stripComments(sql) {
  const out = sql.split("");
  let i = 0;
  let state = "normal"; // normal | line | block | string | dollar
  let tag = "";
  while (i < sql.length) {
    const ch = sql[i];
    if (state === "normal") {
      if (ch === "'") state = "string";
      else if (ch === "$") {
        const m = dollarTagAt(sql, i);
        if (m !== null) {
          tag = m;
          state = "dollar";
          i += tag.length - 1;
        }
      } else if (ch === "-" && sql[i + 1] === "-") {
        state = "line";
        out[i] = " ";
        out[i + 1] = " ";
        i++;
      } else if (ch === "/" && sql[i + 1] === "*") {
        state = "block";
        out[i] = " ";
        out[i + 1] = " ";
        i++;
      }
    } else if (state === "line") {
      if (ch === "\n") state = "normal";
      else out[i] = " ";
    } else if (state === "block") {
      if (ch === "*" && sql[i + 1] === "/") {
        out[i] = " ";
        out[i + 1] = " ";
        i++;
        state = "normal";
      } else if (ch !== "\n") {
        out[i] = " ";
      }
    } else if (state === "string") {
      if (ch === "'") {
        if (sql[i + 1] === "'") i++; // escaped ''
        else state = "normal";
      }
    } else if (state === "dollar") {
      if (sql.startsWith(tag, i)) {
        i += tag.length - 1;
        state = "normal";
      }
    }
    i++;
  }
  return out.join("");
}

// Splits comment-stripped SQL into statements on top-level semicolons,
// respecting string literals ('' escapes) and dollar-quoted bodies.
// Returns [{ text, start }] with start = offset of the first non-space char.
function splitStatements(sql) {
  const stmts = [];
  let start = 0;
  let state = "normal"; // normal | string | dollar
  let tag = "";
  let i = 0;
  while (i < sql.length) {
    const ch = sql[i];
    if (state === "normal") {
      if (ch === "'") state = "string";
      else if (ch === "$") {
        const m = dollarTagAt(sql, i);
        if (m !== null) {
          tag = m;
          state = "dollar";
          i += tag.length - 1;
        }
      } else if (ch === ";") {
        const text = sql.slice(start, i);
        const first = text.search(/\S/);
        if (first !== -1) stmts.push({ text: text.slice(first), start: start + first });
        start = i + 1;
      }
    } else if (state === "string") {
      if (ch === "'") {
        if (sql[i + 1] === "'") i++;
        else state = "normal";
      }
    } else if (state === "dollar") {
      if (sql.startsWith(tag, i)) {
        i += tag.length - 1;
        state = "normal";
      }
    }
    i++;
  }
  const tail = sql.slice(start);
  const first = tail.search(/\S/);
  if (first !== -1) stmts.push({ text: tail.slice(first), start: start + first });
  return stmts;
}

// Blanks the contents of string literals and dollar-quoted bodies so regexes
// and paren/comma scanning never match quoted payload.
function maskLiterals(stmt) {
  const out = stmt.split("");
  let i = 0;
  let state = "normal";
  let tag = "";
  while (i < stmt.length) {
    const ch = stmt[i];
    if (state === "normal") {
      if (ch === "'") state = "string";
      else if (ch === "$") {
        const m = dollarTagAt(stmt, i);
        if (m !== null) {
          tag = m;
          state = "dollar";
          i += tag.length - 1;
        }
      }
    } else {
      out[i] = " ";
      if (state === "string" && ch === "'") {
        if (stmt[i + 1] === "'") {
          i++;
          out[i] = " ";
        } else state = "normal";
      } else if (state === "dollar" && stmt.startsWith(tag, i)) {
        for (let k = 0; k < tag.length; k++) out[i + k] = " ";
        i += tag.length - 1;
        state = "normal";
      }
    }
    i++;
  }
  return out.join("");
}

function lineAt(sql, offset) {
  let line = 1;
  for (let i = 0; i < offset; i++) if (sql[i] === "\n") line++;
  return line;
}

// Splits a paren-balanced body on top-level commas (literals are already
// masked, so no parens/commas can hide inside them).
function splitTopLevel(text) {
  const parts = [];
  let depth = 0;
  let current = "";
  for (const ch of text) {
    if (ch === "(") depth++;
    if (ch === ")") depth--;
    if (ch === "," && depth === 0) {
      parts.push(current);
      current = "";
    } else {
      current += ch;
    }
  }
  if (current.trim() !== "") parts.push(current);
  return parts;
}

const TABLE_CONSTRAINT = /^\s*(constraint|primary|foreign|unique|check|exclude|like)\b/i;

function columnName(def) {
  const quoted = def.match(/^\s*"([^"]*)"/);
  if (quoted) return quoted[1].toLowerCase();
  return ((def.match(/^\s*[^\s(]+/) ?? [""])[0].trim()).toLowerCase();
}

// money-float-type: banned type tokens anywhere in a statement (a type can
// appear in ADD COLUMN, ALTER COLUMN ... TYPE, CREATE TABLE, ...).
function checkMoney(masked, sql, stmtStart) {
  const re = /\b(numeric|decimal|real|double|float[48]?)\b/gi;
  const findings = [];
  let m;
  while ((m = re.exec(masked)) !== null) {
    findings.push(
      finding(
        RULE_MONEY,
        lineAt(sql, stmtStart + m.index),
        `"${m[0].toLowerCase()}" is a floating/decimal type — money is BIGINT kopecks (ADR 0036); if this is a genuine non-money decimal column, record an exemption in tools/migration-lint/domain-rules.mjs`,
      ),
    );
  }
  return findings;
}

// id-column-default: DEFAULT on the id column — CREATE TABLE column defs and
// ALTER TABLE ADD COLUMN / ALTER COLUMN ... SET DEFAULT actions.
function checkIdDefault(masked, sql, stmtStart) {
  const findings = [];
  const create = masked.match(/^create\s+(?:unlogged\s+)?table\s+(?:if\s+not\s+exists\s+)?[^\s(]+\s*\(/i);
  if (create) {
    const bodyStart = create[0].length;
    let depth = 0;
    let bodyEnd = -1;
    for (let k = bodyStart - 1; k < masked.length; k++) {
      if (masked[k] === "(") depth++;
      else if (masked[k] === ")") {
        depth--;
        if (depth === 0) {
          bodyEnd = k;
          break;
        }
      }
    }
    if (bodyEnd !== -1) {
      for (const def of splitTopLevel(masked.slice(bodyStart, bodyEnd))) {
        if (TABLE_CONSTRAINT.test(def)) continue;
        const offset = masked.slice(bodyStart).indexOf(def) + bodyStart;
        const defDefault = /\bdefault\b/i.exec(def);
        if (columnName(def) === "id" && defDefault !== null) {
          findings.push(finding(RULE_ID, lineAt(sql, stmtStart + offset + defDefault.index), ID_DEFAULT_MESSAGE));
        }
      }
    }
    return findings;
  }
  const alter = masked.match(/^alter\s+table\s+(?:only\s+)?(?:if\s+exists\s+)?[^\s]+\s*/i);
  if (alter) {
    for (const action of splitTopLevel(masked.slice(alter[0].length))) {
      const offset = masked.slice(alter[0].length).indexOf(action) + alter[0].length;
      const line = lineAt(sql, stmtStart + offset);
      const actionDefault = /\bdefault\b/i.exec(action);
      if (/^add\s+column\s+(?:if\s+not\s+exists\s+)?"?id"?\b/i.test(action) && actionDefault !== null) {
        findings.push(finding(RULE_ID, lineAt(sql, stmtStart + offset + actionDefault.index), ID_DEFAULT_MESSAGE));
      }
      if (/^alter\s+column\s+"?id"?\s+set\s+default\b/i.test(action)) {
        findings.push(finding(RULE_ID, line, ID_DEFAULT_MESSAGE));
      }
    }
  }
  return findings;
}

function lintFile(file) {
  const sql = readFileSync(file, "utf8");
  const findings = [];
  for (const stmt of splitStatements(stripComments(sql))) {
    const masked = maskLiterals(stmt.text);
    findings.push(...checkMoney(masked, sql, stmt.start));
    findings.push(...checkIdDefault(masked, sql, stmt.start));
  }
  return findings;
}

function main() {
  const files = process.argv.slice(2);
  if (files.length === 0) {
    console.error("usage: node domain-rules.mjs <migration.sql>...");
    process.exit(2);
  }

  let checked = 0;
  let skipped = 0;
  let total = 0;
  for (const file of files) {
    const name = file.split("/").pop();
    if (name.endsWith(".down.sql")) {
      console.log(`domain-rules: skipped ${name} (down migration: deliberate inverse of a linted up file)`);
      skipped++;
      continue;
    }
    if (HISTORICAL_EXEMPT.has(name)) {
      console.log(`domain-rules: exempt ${name} (historical: ${HISTORICAL_EXEMPT.get(name)})`);
      skipped++;
      continue;
    }
    let findings;
    try {
      findings = lintFile(file);
    } catch (err) {
      console.error(`domain-rules: cannot read ${file}: ${err.message}`);
      process.exit(2);
    }
    checked++;
    total += findings.length;
    for (const f of findings) {
      console.log(`${file}:${f.line}: ${f.rule}: ${f.message}`);
    }
  }

  if (total > 0) {
    console.log(`domain-rules: ${total} finding(s) in ${checked} checked file(s), ${skipped} skipped`);
    process.exit(1);
  }
  console.log(`domain-rules: ok (${checked} checked, ${skipped} skipped)`);
}

main();
