ALTER TABLE users ADD COLUMN phone_encrypted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE sms_codes ADD COLUMN phone_encrypted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE login_attempts ADD COLUMN phone_encrypted BOOLEAN NOT NULL DEFAULT FALSE;
