-- Revert 000079: restore DEFAULT gen_random_uuid() on id columns.
ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE login_attempts ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE sessions ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE tariffs ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE user_subscriptions ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE properties ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE tenant_contacts ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE leases ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE recurring_operations ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE operations ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE reminders ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE sent_sms_reminders ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE payment_methods ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE subscription_payments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE property_photos ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE login_codes ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE sent_email_reminders ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE operation_categories ALTER COLUMN id SET DEFAULT gen_random_uuid();
