/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/phone/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendPhoneCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/phone/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyPhoneCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/me/phone/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendPhoneChangeCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/phone/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProperties"];
        put?: never;
        post: operations["createProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dadata/suggestions/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAddressSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProperty"];
        trace?: never;
    };
    "/properties/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unarchiveProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPropertyLeases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}/operations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPropertyOperationsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadPropertyPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePropertyPhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOperationsByProperty"];
        put?: never;
        post: operations["createOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/operations/{operationId}/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOperationReminders"];
        put?: never;
        post: operations["createOperationReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete: operations["deleteOperation"];
        options?: never;
        head?: never;
        patch: operations["updateOperation"];
        trace?: never;
    };
    "/operations/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFinanceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/recurring-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecurringOperationsByProperty"];
        put?: never;
        post: operations["createRecurringOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/recurring-operations/{recurringOperationId}/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecurringOperationReminders"];
        put?: never;
        post: operations["createRecurringOperationReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecurringOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRecurringOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateRecurringOperation"];
        trace?: never;
    };
    "/recurring-operations/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseRecurringOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recurring-operations/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeRecurringOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLeases"];
        put?: never;
        post: operations["createLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateLease"];
        trace?: never;
    };
    "/leases/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases/{id}/deposit-return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["returnLeaseDeposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases/{leaseId}/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLeaseReminders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenantContacts"];
        put?: never;
        post: operations["createTenantContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant-contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTenantContact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTenantContact"];
        trace?: never;
    };
    "/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReminders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders/{reminderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteReminder"];
        options?: never;
        head?: never;
        patch: operations["updateReminder"];
        trace?: never;
    };
    "/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTariffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/auto-renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["toggleAutoRenew"];
        trace?: never;
    };
    "/subscription/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeTariff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSubscriptionPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPaymentMethods"];
        put?: never;
        post: operations["addPaymentMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/payment-methods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePaymentMethod"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/payment-methods/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activatePaymentMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subscription/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminSubscriptionPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subscription/payments/{paymentId}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refundSubscriptionPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subscription/payments/{paymentId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncSubscriptionPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/fake-subscription-payment/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmFakeSubscriptionPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/payment/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["handlePaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SendPhoneCodeRequest: {
            /** @example +79990001122 */
            phone: string;
        };
        VerifyPhoneCodeRequest: {
            phone: string;
            /** @example 123456 */
            code: string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            phone: string;
            /** @enum {string} */
            role: "owner" | "admin";
            name?: string | null;
            surname?: string | null;
            patronymic?: string | null;
            email?: string | null;
            subscription?: components["schemas"]["Subscription"];
        };
        UserUpdateRequest: {
            name?: string | null;
            surname?: string | null;
            patronymic?: string | null;
            /** @description Email is stored in lowercase. */
            email?: string | null;
        };
        SendPhoneChangeCodeRequest: {
            /** @example +79990001122 */
            phone: string;
        };
        ChangePhoneRequest: {
            /** @example +79990001122 */
            phone: string;
            /** @example 123456 */
            code: string;
        };
        Tariff: {
            /** @enum {string} */
            name: "basic" | "pro" | "business";
            activePropertyLimit: number;
            monthlyPriceKopecks: number;
            yearlyPriceKopecks: number;
        };
        Subscription: {
            tariff: components["schemas"]["Tariff"];
            /** @enum {string} */
            status: "active" | "grace" | "blocked" | "cancelled";
            /** Format: date-time */
            validUntil?: string | null;
            autoRenewEnabled: boolean;
            pendingTariff?: components["schemas"]["Tariff"];
            /** Format: date-time */
            pendingChangeAt?: string | null;
            /** @enum {string|null} */
            pendingPeriod?: "month" | "year" | null;
            activePaymentMethod?: components["schemas"]["PaymentMethod"];
        };
        PaymentMethod: {
            /** Format: uuid */
            id: string;
            provider: string;
            displayMask: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        SubscriptionPayment: {
            /** Format: uuid */
            id: string;
            tariff: components["schemas"]["Tariff"];
            /** @enum {string} */
            period: "month" | "year";
            amountKopecks: number;
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed" | "refunded" | "partial_refunded";
            provider: string;
            /** Format: date-time */
            createdAt: string;
        };
        ChangeTariffRequest: {
            /** @enum {string} */
            tariffName: "basic" | "pro" | "business";
            /** @enum {string} */
            period: "month" | "year";
        };
        ChangeTariffResponse: {
            /** Format: uuid */
            paymentId?: string | null;
            confirmUrl?: string | null;
        };
        AutoRenewRequest: {
            enabled: boolean;
        };
        AddPaymentMethodRequest: {
            /**
             * @description Raw provider token for synchronous providers (e.g. fake).
             *     Ignored for providers that use a bank-form flow such as T-Kassa.
             */
            providerToken?: string;
        };
        AddPaymentMethodResponse: {
            confirmUrl?: string | null;
            paymentMethod?: components["schemas"]["PaymentMethod"];
        };
        TariffsResponse: {
            items: components["schemas"]["Tariff"][];
        };
        PaymentMethodsResponse: {
            items: components["schemas"]["PaymentMethod"][];
        };
        SubscriptionPaymentsResponse: {
            items: components["schemas"]["SubscriptionPayment"][];
        };
        AdminSubscriptionPayment: {
            /** Format: uuid */
            id: string;
            tariff: components["schemas"]["Tariff"];
            /** @enum {string} */
            period: "month" | "year";
            amountKopecks: number;
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed" | "refunded" | "partial_refunded";
            provider: string;
            /** Format: uuid */
            userId: string;
            userPhone: string;
            /** Format: date-time */
            createdAt: string;
        };
        AdminSubscriptionPaymentsResponse: {
            items: components["schemas"]["AdminSubscriptionPayment"][];
            total: number;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            requestId?: string;
        };
        AddressSuggestionsResponse: {
            suggestions: components["schemas"]["AddressSuggestion"][];
        };
        AddressSuggestion: {
            value: string;
            city?: string;
        };
        PropertyCreateRequest: {
            name: string;
            /** @enum {string} */
            type: "apartment" | "room" | "apartments" | "house" | "commercial" | "office" | "warehouse" | "garage" | "parking" | "land";
            address: string;
            description?: string;
        };
        PropertyUpdateRequest: {
            name?: string;
            /** @enum {string} */
            type?: "apartment" | "room" | "apartments" | "house" | "commercial" | "office" | "warehouse" | "garage" | "parking" | "land";
            address?: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "maintenance";
        };
        PropertyResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            type: "apartment" | "room" | "apartments" | "house" | "commercial" | "office" | "warehouse" | "garage" | "parking" | "land";
            address: string;
            description?: string;
            /** @enum {string} */
            status: "active" | "maintenance" | "archived";
            /** @enum {string} */
            occupancy: "free" | "occupied";
            photos?: components["schemas"]["PropertyPhoto"][];
            active_lease: components["schemas"]["LeaseResponse"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PropertyPhoto: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
        };
        PropertyPhotosResponse: {
            items: components["schemas"]["PropertyPhoto"][];
        };
        PropertyLeasesResponse: {
            items: components["schemas"]["LeaseResponse"][];
        };
        PropertyOperationsSummaryResponse: {
            monthly_profit_kopecks: number;
            all_time_profit_kopecks: number;
            overdue_rent_count: number;
            overdue_total_count: number;
            /** Format: date */
            next_payment_date?: string | null;
        };
        LeaseCreateRequest: {
            /** Format: uuid */
            property_id: string;
            /** Format: uuid */
            tenant_contact_id?: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string;
            rent_amount_kopecks: number;
            /** @default 0 */
            deposit_amount_kopecks: number;
            payment_day: number;
            comment?: string;
        };
        LeaseUpdateRequest: {
            /** Format: uuid */
            tenant_contact_id?: string;
            /** @default false */
            clear_tenant_contact: boolean;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            rent_amount_kopecks?: number;
            deposit_amount_kopecks?: number;
            payment_day?: number;
            comment?: string;
        };
        LeaseResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            property_id: string;
            /** Format: uuid */
            owner_id: string;
            tenant_contact: components["schemas"]["TenantContactResponse"] | null;
            /** @enum {string} */
            status: "awaiting_start" | "active" | "requires_action" | "completed" | "archived";
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            rent_amount_kopecks: number;
            deposit_amount_kopecks: number;
            payment_day: number;
            comment?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LeasesResponse: {
            items: components["schemas"]["LeaseResponse"][];
        };
        TenantContactCreateRequest: {
            name: string;
            surname?: string;
            patronymic?: string;
            phone?: string;
            email?: string;
            comment?: string;
        };
        TenantContactUpdateRequest: {
            name?: string;
            surname?: string;
            patronymic?: string;
            phone?: string;
            email?: string;
            comment?: string;
        };
        TenantContactResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            name: string;
            surname: string | null;
            patronymic: string | null;
            phone: string | null;
            email: string | null;
            comment: string | null;
            is_active: boolean;
            active_lease: components["schemas"]["LeaseResponse"] | null;
            last_lease: components["schemas"]["LeaseResponse"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TenantContactsResponse: {
            items: components["schemas"]["TenantContactResponse"][];
        };
        PropertiesResponse: {
            items: components["schemas"]["PropertyResponse"][];
        };
        /** @enum {string} */
        OperationType: "income" | "expense";
        /** @enum {string} */
        OperationCategory: "rent" | "other_income" | "utilities" | "repair" | "tax" | "other_expense" | "deposit_return";
        /** @enum {string} */
        OperationStatus: "pending" | "overdue" | "paid" | "received";
        OperationCreateRequest: {
            type: components["schemas"]["OperationType"];
            category: components["schemas"]["OperationCategory"];
            name: string;
            amount_kopecks: number;
            /** Format: date */
            operation_date: string;
            comment?: string;
            /** Format: uuid */
            lease_id?: string;
        };
        OperationUpdateRequest: {
            type?: components["schemas"]["OperationType"];
            category?: components["schemas"]["OperationCategory"];
            name?: string;
            amount_kopecks?: number;
            /** Format: date */
            operation_date?: string;
            comment?: string;
            /** Format: uuid */
            lease_id?: string;
        };
        OperationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            /** Format: uuid */
            property_id: string;
            /** Format: uuid */
            lease_id?: string | null;
            /** Format: uuid */
            recurring_operation_id?: string | null;
            type: components["schemas"]["OperationType"];
            category: components["schemas"]["OperationCategory"];
            name: string;
            amount_kopecks: number;
            /** Format: date */
            operation_date: string;
            status: components["schemas"]["OperationStatus"];
            comment?: string | null;
            is_exception: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OperationsResponse: {
            items: components["schemas"]["OperationResponse"][];
        };
        RecurringOperationCreateRequest: {
            type: components["schemas"]["OperationType"];
            category: components["schemas"]["OperationCategory"];
            name: string;
            amount_kopecks: number;
            /** Format: date */
            start_date: string;
            payment_day: number;
            /** Format: date */
            end_date?: string;
            comment?: string;
            /** @enum {string} */
            periodicity?: "monthly" | "yearly";
        };
        RecurringOperationUpdateRequest: {
            type?: components["schemas"]["OperationType"];
            category?: components["schemas"]["OperationCategory"];
            name?: string;
            amount_kopecks?: number;
            /** Format: date */
            start_date?: string;
            payment_day?: number;
            /** Format: date */
            end_date?: string;
            comment?: string;
            /** @enum {string} */
            periodicity?: "monthly" | "yearly";
            /** Format: date */
            apply_from_date?: string;
        };
        RecurringOperationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            /** Format: uuid */
            property_id: string;
            /** Format: uuid */
            lease_id?: string | null;
            type: components["schemas"]["OperationType"];
            category: components["schemas"]["OperationCategory"];
            name: string;
            amount_kopecks: number;
            /** Format: date */
            start_date: string;
            payment_day: number;
            /** Format: date */
            end_date?: string | null;
            /** @enum {string} */
            periodicity: "monthly" | "yearly";
            /** @enum {string} */
            status: "active" | "paused";
            comment?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RecurringOperationsResponse: {
            items: components["schemas"]["RecurringOperationResponse"][];
        };
        ReminderResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            /** @enum {string} */
            target_type: "operation" | "recurring_operation" | "lease";
            /** Format: uuid */
            operation_id?: string | null;
            /** Format: uuid */
            recurring_operation_id?: string | null;
            /** Format: uuid */
            lease_id?: string | null;
            /** Format: uuid */
            property_id?: string | null;
            /** @enum {string} */
            event_type: "operation_due" | "operation_overdue" | "lease_expiring" | "lease_requires_action";
            /** @enum {string} */
            status: "pending" | "sent" | "failed" | "cancelled";
            /** Format: date-time */
            scheduled_at: string;
            /** Format: date-time */
            sent_at?: string | null;
            failed_attempts: number;
            /** Format: date-time */
            next_attempt_at?: string | null;
            message_title: string;
            message_body: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ReminderCreateRequest: {
            /** Format: date */
            reminder_date: string;
        };
        ReminderUpdateRequest: {
            /** Format: date */
            reminder_date: string;
        };
        RefundSubscriptionPaymentRequest: {
            /** @description Optional partial refund amount in kopecks. If omitted, the full payment amount is refunded. */
            amount_kopecks?: number;
        };
        RemindersResponse: {
            items: components["schemas"]["ReminderResponse"][];
        };
        FinanceReportResponse: {
            period: components["schemas"]["FinanceReportPeriod"];
            totals: components["schemas"]["FinanceReportTotals"];
            by_property: components["schemas"]["FinanceReportPropertyRow"][];
            by_category: components["schemas"]["FinanceReportCategoryRow"][];
            by_month: components["schemas"]["FinanceReportMonthRow"][];
        };
        FinanceReportPeriod: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        FinanceReportTotals: {
            income_kopecks: number;
            expense_kopecks: number;
            profit_kopecks: number;
        };
        FinanceReportPropertyRow: {
            /** Format: uuid */
            property_id: string;
            income_kopecks: number;
            expense_kopecks: number;
            profit_kopecks: number;
        };
        FinanceReportCategoryRow: {
            type: components["schemas"]["OperationType"];
            category: components["schemas"]["OperationCategory"];
            total_kopecks: number;
        };
        FinanceReportMonthRow: {
            /** Format: date */
            month: string;
            income_kopecks: number;
            expense_kopecks: number;
            profit_kopecks: number;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Too many requests */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Subscription is blocked; renew to continue mutating data */
        SubscriptionBlocked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sendPhoneCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendPhoneCodeRequest"];
            };
        };
        responses: {
            /** @description Code sent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    verifyPhoneCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPhoneCodeRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions logged out */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    sendPhoneChangeCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendPhoneChangeCodeRequest"];
            };
        };
        responses: {
            /** @description Code sent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    changePhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePhoneRequest"];
            };
        };
        responses: {
            /** @description Phone changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Properties list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertiesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyCreateRequest"];
            };
        };
        responses: {
            /** @description Property created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
        };
    };
    getAddressSuggestions: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Address suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressSuggestionsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyUpdateRequest"];
            };
        };
        responses: {
            /** @description Property updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    archiveProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    unarchiveProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property unarchived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    listPropertyLeases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property leases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyLeasesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPropertyOperationsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property operations summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyOperationsSummaryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadPropertyPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Photo uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyPhoto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deletePropertyPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listOperationsByProperty: {
        parameters: {
            query?: {
                status?: components["schemas"]["OperationStatus"][];
                type?: components["schemas"]["OperationType"][];
                category?: components["schemas"]["OperationCategory"][];
                from?: string;
                to?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operations list for property */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationCreateRequest"];
            };
        };
        responses: {
            /** @description Operation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    listOperationReminders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemindersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createOperationReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                operationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderCreateRequest"];
            };
        };
        responses: {
            /** @description Reminder created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    listOperations: {
        parameters: {
            query?: {
                type?: components["schemas"]["OperationType"][];
                status?: components["schemas"]["OperationStatus"][];
                category?: components["schemas"]["OperationCategory"][];
                property_id?: string;
                from?: string;
                to?: string;
                recurring_operation_id?: string;
                lease_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operations list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    updateOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationUpdateRequest"];
            };
        };
        responses: {
            /** @description Operation updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    completeOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Operation completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getFinanceReport: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finance report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinanceReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRecurringOperationsByProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring operations list for property */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOperationsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createRecurringOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringOperationCreateRequest"];
            };
        };
        responses: {
            /** @description Recurring operation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOperationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    listRecurringOperationReminders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                recurringOperationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemindersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createRecurringOperationReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
                recurringOperationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderCreateRequest"];
            };
        };
        responses: {
            /** @description Reminders created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemindersResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    listRecurringOperations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring operations list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOperationsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRecurringOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring operation details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOperationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRecurringOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringOperationUpdateRequest"];
            };
        };
        responses: {
            /** @description Recurring operation updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOperationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    pauseRecurringOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring operation paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOperationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    resumeRecurringOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurring operation resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOperationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    listLeases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leases list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeasesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createLease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseCreateRequest"];
            };
        };
        responses: {
            /** @description Lease created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
        };
    };
    getLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lease details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseUpdateRequest"];
            };
        };
        responses: {
            /** @description Lease updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    completeLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lease completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    returnLeaseDeposit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deposit returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    listLeaseReminders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemindersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTenantContacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant contacts list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantContactsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTenantContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantContactCreateRequest"];
            };
        };
        responses: {
            /** @description Tenant contact created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantContactResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            409: components["responses"]["Conflict"];
        };
    };
    getTenantContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant contact details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantContactResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTenantContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantContactUpdateRequest"];
            };
        };
        responses: {
            /** @description Tenant contact updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantContactResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listReminders: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemindersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminder cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
        };
    };
    updateReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reminderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderUpdateRequest"];
            };
        };
        responses: {
            /** @description Reminder updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["SubscriptionBlocked"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listTariffs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tariffs list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current subscription */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    toggleAutoRenew: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoRenewRequest"];
            };
        };
        responses: {
            /** @description Auto-renew updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    cancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    changeTariff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeTariffRequest"];
            };
        };
        responses: {
            /** @description Tariff change initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeTariffResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listSubscriptionPayments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription payments list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPaymentsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listPaymentMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment methods list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addPaymentMethod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPaymentMethodRequest"];
            };
        };
        responses: {
            /** @description Payment method added or confirmation URL returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddPaymentMethodResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deletePaymentMethod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment method deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    activatePaymentMethod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment method activated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAdminSubscriptionPayments: {
        parameters: {
            query?: {
                status?: "pending" | "succeeded" | "failed" | "refunded" | "partial_refunded";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin subscription payments list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubscriptionPaymentsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refundSubscriptionPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefundSubscriptionPaymentRequest"];
            };
        };
        responses: {
            /** @description Payment refunded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    syncSubscriptionPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment synchronized */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    confirmFakeSubscriptionPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    handlePaymentWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Webhook processed; response body is provider-specific */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "text/plain": string;
                };
            };
        };
    };
}
