export const ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  properties: '/properties',
  property: (id: string) => `/properties/${id}`,
  propertyArchive: '/properties/archive',
  propertyNew: '/properties/new',
  propertyEdit: (id: string) => `/properties/${id}/edit`,
  leaseNew: '/leases/new',
  tenants: '/tenants',
  tenant: (id: string) => `/tenants/${id}`,
  tenantNew: '/tenants/new',
  tenantEdit: (id: string) => `/tenants/${id}/edit`,
  finance: '/finance',
  profile: '/profile',
  profilePersonal: '/profile/personal',
  profileAccount: '/profile/account',
  profileChangePhone: '/profile/account/phone',
  profileTariff: '/profile/tariff',
  profileTariffChange: '/profile/tariff/change',
  profileTariffChangeSuccess: '/profile/tariff/change/success',
  profilePaymentMethods: '/profile/tariff/payment-methods',
  profilePaymentMethodsAdd: '/profile/tariff/payment-methods/add',
  profilePayments: '/profile/tariff/payments',
  profilePaymentDetail: (id: string) => `/profile/tariff/payments/${id}`,
  profileSupport: '/profile/support',
  profileInfo: '/profile/info',
  profilePrivacy: '/profile/info/privacy',
  profileTerms: '/profile/info/terms',
} as const;
