export const ROUTES = {
  login: '/login',
  properties: '/properties',
  property: (id: string) => `/properties/${id}`,
  propertyArchive: '/properties/archive',
  propertyNew: '/properties/new',
  propertyEdit: (id: string) => `/properties/${id}/edit`,
  propertyContactsNew: (id: string) => `/properties/${id}/contacts/new`,
  propertyContactEdit: (propertyId: string, contactId: string) =>
    `/properties/${propertyId}/contacts/${contactId}/edit`,
  profile: '/profile',
  profilePersonal: '/profile/personal',
  profileNotifications: '/profile/notifications',
  profileAccount: '/profile/account',
  profileChangePhone: '/profile/account/phone',
  profileTariff: '/profile/tariff',
  profileTariffChange: '/profile/tariff/change',
  profileTariffChangeSuccess: '/profile/tariff/change/success',
  profilePaymentMethods: '/profile/tariff/payment-methods',
  profilePaymentMethodsAdd: '/profile/tariff/payment-methods/add',
  profilePayments: '/profile/tariff/payments',
  profilePaymentDetail: (id: string) => `/profile/tariff/payments/${id}`,
  profileInfo: '/profile/info',
  profilePrivacy: '/profile/info/privacy',
  profileTerms: '/profile/info/terms',
} as const;
