export const ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  properties: '/properties',
  property: (id: string) => `/properties/${id}`,
  propertyArchive: '/properties/archive',
  propertyNew: '/properties/new',
  propertyEdit: (id: string) => `/properties/${id}/edit`,
  propertyContactsNew: (id: string) => `/properties/${id}/contacts/new`,
  propertyContactEdit: (propertyId: string, contactId: string) =>
    `/properties/${propertyId}/contacts/${contactId}/edit`,
  propertyLeases: (id: string) => `/properties/${id}/leases`,
  leaseNew: '/leases/new',
  lease: (id: string) => `/leases/${id}`,
  leaseEdit: (id: string) => `/leases/${id}/edit`,
  tenants: '/tenants',
  tenant: (id: string) => `/tenants/${id}`,
  tenantNew: '/tenants/new',
  tenantEdit: (id: string) => `/tenants/${id}/edit`,
  finance: '/finance',
  financeOperations: '/finance/operations',
  financeCreateOperation: '/finance/create-operation',
  financeOperation: (id: string) => `/finance/operations/${id}`,
  financeOperationEdit: (id: string) => `/finance/operations/${id}/edit`,
  financeRecurringOperation: (id: string) => `/finance/operations/recurring/${id}`,
  financeRecurringOperationEdit: (id: string) => `/finance/operations/recurring/${id}/edit`,
  propertyOperations: (id: string) => `/properties/${id}/operations`,
  profile: '/profile',
  profilePersonal: '/profile/personal',
  profileNotifications: '/profile/notifications',
  profileAccount: '/profile/account',
  profileChangePhone: '/profile/account/phone',
  profileTariff: '/profile/tariff',
  profileTariffChange: '/profile/tariff/change',
  profileTariffChangeSuccess: '/profile/tariff/change/success',
  profilePaymentMethods: '/profile/tariff/payment-methods',
  profilePaymentMethodsAdd: '/profile/tariff/payment-methods/add',
  profilePayments: '/profile/tariff/payments',
  profilePaymentDetail: (id: string) => `/profile/tariff/payments/${id}`,
  profileSupport: '/profile/support',
  profileInfo: '/profile/info',
  profilePrivacy: '/profile/info/privacy',
  profileTerms: '/profile/info/terms',
} as const;
