// Worktree slot helpers for parallel dev checkouts — the executable form of
// the contract in docs/agents/parallel-dev.md:
//   port = BASE[service] + OFFSET[role] + N, slot 0 = the main checkout with
//   its historical ports untouched.
// The Makefile and make worktree-new reach this through the CLIs
// (dev-env.mjs, worktree-new.mjs); the tests import the functions directly.

import fs from "node:fs";
import path from "node:path";

const DEV_BASE = { postgres: 5440, backend: 8090, frontend: 3020 };
const E2E_OFFSET = 5;

// Slot 0 never gets formula ports: the main checkout keeps the historical
// manual allocations (5433/5435/5436, 8080/8081, 3000/3010) so existing
// workflows and docs stay valid.
const SLOT0 = {
  slot: 0,
  devPgPort: 5433,
  devBackendPort: 8080,
  devFrontendPort: 3000,
  e2ePgPort: 5436,
  e2eBackendPort: 8081,
  e2eFrontendPort: 3010,
  composeProject: "arenda-local",
  e2eComposeProject: "arenda-e2e",
};

export function slotConfig(slot) {
  if (!Number.isInteger(slot) || slot < 0 || slot > 9) {
    throw new RangeError(`slot must be an integer 0..9, got ${String(slot)}`);
  }
  if (slot === 0) return { ...SLOT0 };
  return {
    slot,
    devPgPort: DEV_BASE.postgres + slot,
    devBackendPort: DEV_BASE.backend + slot,
    devFrontendPort: DEV_BASE.frontend + slot,
    e2ePgPort: DEV_BASE.postgres + E2E_OFFSET + slot,
    e2eBackendPort: DEV_BASE.backend + E2E_OFFSET + slot,
    e2eFrontendPort: DEV_BASE.frontend + E2E_OFFSET + slot,
    composeProject: `arenda-wt${slot}`,
    e2eComposeProject: `arenda-e2e-wt${slot}`,
  };
}

// .env semantics that matter here: KEY=VALUE lines, `#` comments, blank lines,
// optional matching quotes, and the last occurrence of a key wins — the same
// last-wins rule both shell sourcing and compose --env-file apply, which is
// what makes the generated slot block override the copied env.
export function parseEnvFile(text) {
  const env = {};
  for (const rawLine of String(text).split("\n")) {
    const line = rawLine.replace(/\r$/, "").trim();
    if (line === "" || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (value.length >= 2 && value.startsWith(value.at(-1)) && '"\''.includes(value.at(0))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

// null = no claim in this env; a present but malformed claim throws — the
// caller names the file, a corrupt registry must not silently claim or free
// a slot.
export function slotFromEnv(env) {
  if (!(env && "AREND_SLOT" in env)) return null;
  const raw = env.AREND_SLOT;
  const slot = Number(raw);
  if (!Number.isInteger(slot) || slot < 0 || slot > 9) {
    throw new Error(`invalid AREND_SLOT value "${raw}" (expected an integer 0..9)`);
  }
  return slot;
}

// DATABASE_URL of the slot database. Credentials come from the copied env's
// POSTGRES_USER/PASSWORD/DB (default arenda) so a checkout with custom
// credentials produces a working pair of values; both the generated .env
// block and worktree-new's printed facts go through this single source.
export function slotDatabaseUrl(cfg, baseEnv) {
  const user = encodeURIComponent(baseEnv.POSTGRES_USER || "arenda");
  const password = encodeURIComponent(baseEnv.POSTGRES_PASSWORD || "arenda");
  const db = encodeURIComponent(baseEnv.POSTGRES_DB || "arenda");
  return `postgres://${user}:${password}@localhost:${cfg.devPgPort}/${db}?sslmode=disable`;
}

// The override block appended to a worktree's .env: the copied env stays
// untouched above it, and the last occurrence of each variable wins (both in
// shell sourcing and in compose --env-file).
export function envOverrideBlock(cfg, baseEnv) {
  const { devPgPort, devBackendPort, e2ePgPort, e2eBackendPort, e2eFrontendPort } = cfg;
  return [
    `# --- worktree slot ${cfg.slot} (generated by make worktree-new; docs/agents/parallel-dev.md) ---`,
    "# Keep this block last: the last occurrence of a variable wins, both in",
    "# shell sourcing (`set -a; . ./.env`) and in `docker compose --env-file .env`.",
    `AREND_SLOT=${cfg.slot}`,
    `POSTGRES_PORT=${devPgPort}`,
    `DATABASE_URL=${slotDatabaseUrl(cfg, baseEnv)}`,
    `HTTP_ADDR=:${devBackendPort}`,
    `APP_BASE_URL=http://localhost:${devBackendPort}`,
    `BACKEND_URL=http://localhost:${devBackendPort}`,
    `COMPOSE_PROJECT_NAME=${cfg.composeProject}`,
    `E2E_PG_PORT=${e2ePgPort}`,
    `E2E_BACKEND_PORT=${e2eBackendPort}`,
    `E2E_FRONTEND_PORT=${e2eFrontendPort}`,
    `E2E_COMPOSE_PROJECT=${cfg.e2eComposeProject}`,
    "",
  ].join("\n");
}

// The six host ports a slot owns: the dev role (postgres, backend, frontend)
// then the e2e role. The worktree-new preflight probes exactly these; the
// teardown recipe (docs/agents/parallel-dev.md) walks them to find a slot's
// orphaned processes.
export function slotPorts(cfg) {
  return [
    cfg.devPgPort,
    cfg.devBackendPort,
    cfg.devFrontendPort,
    cfg.e2ePgPort,
    cfg.e2eBackendPort,
    cfg.e2eFrontendPort,
  ];
}

// Port preflight on top of the registry scan (#489 live check): the .env
// registry says nothing about who actually listens, and a slot handed out
// over a foreign listener would let the e2e runner's free_port() kill that
// process. Walk the candidates in order and take the first whose six ports
// have no listener, per probe(port) → pid array (empty = free). probe may
// return null when it cannot run at all (no lsof) — that aborts the
// preflight with unavailable: true so the caller can warn and fall back.
// Every held candidate comes back in `blocked` so the caller can warn with
// the holding pids.
export function selectSlotByPorts(candidateSlots, probe) {
  const blocked = [];
  for (const slot of candidateSlots) {
    const cfg = slotConfig(slot);
    const busyPorts = [];
    for (const port of slotPorts(cfg)) {
      const pids = probe(port);
      if (pids === null) return { unavailable: true, slot: null, cfg: null, blocked };
      if (pids.length > 0) busyPorts.push({ port, pids });
    }
    if (busyPorts.length === 0) return { unavailable: false, slot, cfg, blocked };
    blocked.push({ slot, busyPorts });
  }
  return { unavailable: false, slot: null, cfg: null, blocked };
}

// The registry is the set of .env files itself (docs/agents/parallel-dev.md):
// the checkout's root .env plus every .worktrees/<name>/.env. Returns the
// taken slots (slot → file) and the free N of 1..9 in order (empty when the
// range is exhausted). Duplicate or malformed claims throw.
export function scanSlotRegistry(rootDir) {
  const taken = new Map();
  const candidates = [path.join(rootDir, ".env")];
  const worktreesDir = path.join(rootDir, ".worktrees");
  if (fs.existsSync(worktreesDir)) {
    for (const entry of fs.readdirSync(worktreesDir).sort()) {
      candidates.push(path.join(worktreesDir, entry, ".env"));
    }
  }
  for (const file of candidates) {
    if (!fs.existsSync(file)) continue;
    let slot;
    try {
      slot = slotFromEnv(parseEnvFile(fs.readFileSync(file, "utf8")));
    } catch (err) {
      throw new Error(`${file}: ${err.message}`);
    }
    if (slot === null || slot === 0) continue;
    if (taken.has(slot)) {
      throw new Error(
        `duplicate AREND_SLOT=${slot} claim: ${taken.get(slot)} and ${file} — fix one of them by hand`,
      );
    }
    taken.set(slot, file);
  }
  const freeSlots = [];
  for (let free = 1; free <= 9; free++) {
    if (!taken.has(free)) freeSlots.push(free);
  }
  return { taken, freeSlots };
}

